import type {
  // Assuming 'Course' and other base types are defined as before
  Course,
  CoursePrefix,
  CurriculumSummary,
  ElectiveCourseGroup,
  PerformanceEvaluation,
  ProgramDetails,
  Semester,
} from '@/app/(programs)/_config/curriculum';

// This is the new, more descriptive type for the cse electives

export const cseSemesterInfo = {
  spring: 'January-April',
  summer: 'May-August',
  fall: 'September-December',
};

export const cseRegularProgramDetails: ProgramDetails = {
  degreeName: 'Bachelor of Science in cse Engineering',
  duration: {
    years: 4,
    semesters: 12,
  },
  creditHours: 160.5,
  courseLoad: '16 Weeks/Semester',
  minimumGPA: 2.5,
  backgroundStudents: 'For H.S.C. Background Students',
};

export const cseEveningProgramDetails: ProgramDetails = {
  degreeName: 'Bachelor of Science in cse Engineering',
  duration: {
    years: 4,
    semesters: 12,
  },
  creditHours: 140.0,
  courseLoad: '16 Weeks/Semester',
  minimumGPA: 2.5,
  backgroundStudents: 'For Diploma in Engg. Background Students',
  waiverInfo:
    '19 credits are waived for students with a Diploma in Engineering background.',
};

export const csePerformanceEvaluation: PerformanceEvaluation[] = [
  {
    category: '(a) Theory Courses:',
    criteria: [
      {
        item: 'Class participation (i.e. attendance)',
        percentage: '20%',
      },
      {
        item: 'Class tests, presentations and assignments',
        percentage: '20%',
      },
      { item: 'Midterm Examination', percentage: '30%' },
      { item: 'Final Examination', percentage: '30%' },
    ],
  },
  {
    category: '(b) Courses on Laboratory/Sessional/Field Work:',
    criteria: [
      { item: 'Class participation and attendance', percentage: '20%' },
      { item: 'Quiz', percentage: '20%' },
      { item: 'Viva Voce', percentage: '20%' },
      { item: 'Performance/Reports', percentage: '40%' },
    ],
  },
  {
    category: '(c) Project and Thesis:',
    criteria: [
      { item: 'Attendance', percentage: '10%' },
      { item: 'Presentation and Viva Voce', percentage: '20%' },
      { item: 'Co-Supervisor', percentage: '20%' },
      { item: 'Supervisor', percentage: '50%' },
    ],
  },
];

export const cseCoreCoursesData: Course[] = [
  {
    sl: 1,
    code: 'CSE 100',
    title: 'Introduction to Computer Systems',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 2,
    code: 'CSE 123',
    title: 'Discrete Mathematics',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 3,
    code: 'CSE 121',
    title: 'Structured Programming Language',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 4,
    code: 'CSE 122',
    title: 'Structured Programming Language Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 5,
    code: 'CSE 131',
    title: 'Data Structures',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 6,
    code: 'CSE 132',
    title: 'Data Structures Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 7,
    code: 'CSE 211',
    title: 'Object Oriented Programming Language',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 8,
    code: 'CSE 212',
    title: 'Object Oriented Programming Language Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 9,
    code: 'CSE 213',
    title: 'Digital Logic Design',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 10,
    code: 'CSE 214',
    title: 'Digital Logic Design Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 11,
    code: 'CSE 221',
    title: 'Algorithms',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 12,
    code: 'CSE 222',
    title: 'Algorithms Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 13,
    code: 'CSE 223',
    title: 'Database Management Systems',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 14,
    code: 'CSE 224',
    title: 'Database Management Systems Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 15,
    code: 'CSE 231',
    title: 'Operating Systems',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 16,
    code: 'CSE 232',
    title: 'Operating Systems Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 17,
    code: 'CSE 233',
    title: 'System Analysis and Design',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 18,
    code: 'CSE 234',
    title: 'System Analysis and Design Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 19,
    code: 'CSE 235',
    title: 'Computer Architecture',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 20,
    code: 'CSE 236',
    title: 'Assembly Language Programming Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 21,
    code: 'CSE 305',
    title: 'Numerical Analysis',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 22,
    code: 'CSE 311',
    title: 'Artificial Intelligence',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 23,
    code: 'CSE 312',
    title: 'Artificial Intelligence Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 24,
    code: 'CSE 313',
    title: 'Microprocessors and Microcontroller',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 25,
    code: 'CSE 314',
    title: 'Microprocessors and Microcontroller Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 26,
    code: 'CSE 315',
    title: 'Theory of Computation',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 27,
    code: 'CSE 317',
    title: 'Data Communication',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 28,
    code: 'CSE 321',
    title: 'Software Engineering and Information System Design',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 29,
    code: 'CSE 322',
    title: 'Software Engineering and Information System Design Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 30,
    code: 'CSE 323',
    title: 'Compiler',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 31,
    code: 'CSE 324',
    title: 'Compiler Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 32,
    code: 'CSE 325',
    title: 'Digital System Design',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 33,
    code: 'CSE 326',
    title: 'Digital System Design Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 34,
    code: 'CSE 331',
    title: 'Computer Networks',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 35,
    code: 'CSE 332',
    title: 'Computer Networks Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 36,
    code: 'CSE 333',
    title: 'Pattern Recognition',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 37,
    code: 'CSE 334',
    title: 'Pattern Recognition Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 38,
    code: 'CSE 335',
    title: 'Computer Graphics',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 39,
    code: 'CSE 336',
    title: 'Computer Graphics Sessional',
    credits: 1.5,
    contactHours: 0,
  },
];

export const cseFoundationCoursesData: Course[] = [
  {
    sl: 1,
    code: 'MATH 101',
    title: 'Mathematics-I (Differential and Integral Calculus)',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 2,
    code: 'MATH 103',
    title: 'Mathematics-II (Ordinary and Partial Differential Equations)',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 3,
    code: 'MATH 105',
    title: 'Mathematics-III (Matrices, Vector Analysis and Fourier Series)',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 4,
    code: 'MATH 207',
    title: 'Mathematics-IV (Complex Variable and Laplace Transform)',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 5,
    code: 'MATH 221',
    title: 'Mathematics-V (Statistics and Coordinate Geometry)',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 6,
    code: 'PHY 101',
    title: 'Physics',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 7,
    code: 'PHY 102',
    title: 'Physics Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 8,
    code: 'CHE 101',
    title: 'Chemistry',
    credits: 3,
    contactHours: 0,
  },
];

export const cseGeneralEducationCourses: Course[] = [
  {
    sl: 1,
    code: 'ENG 101',
    title: 'Foundation English',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 2,
    code: 'MGT 201',
    title: 'Industrial and Operational Management',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 3,
    code: 'ECO 201',
    title: 'Engineering Economics',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 4,
    code: 'ACT 201',
    title: 'Financial & Managerial Accounting',
    credits: 3,
    contactHours: 0,
  },
];

export const cseBasicScienceCourses: Course[] = [
  {
    sl: 1,
    code: 'PHY 101',
    title: 'Physics-I: General Physics',
    credits: 3,
    contactHours: 3,
  },
  {
    sl: 2,
    code: 'PHY 102',
    title: 'Physics Lab',
    credits: 1,
    contactHours: 2,
  },
  {
    sl: 3,
    code: 'PHY 103',
    title: 'Physics-II: Modern Physics',
    credits: 3,
    contactHours: 3,
  },
  {
    sl: 4,
    code: 'CHM 101',
    title: 'General Chemistry',
    credits: 3,
    contactHours: 3,
  },
  {
    sl: 5,
    code: 'CHM 102',
    title: 'Chemistry Lab',
    credits: 1,
    contactHours: 2,
  },
  {
    sl: 6,
    code: 'MTH 101',
    title: 'Math-I: Differential and Integral Calculus',
    credits: 3,
    contactHours: 3,
  },
  {
    sl: 7,
    code: 'MTH 103',
    title: 'Math-II: Linear Algebra, Matrix and Statistics',
    credits: 3,
    contactHours: 3,
  },
  {
    sl: 8,
    code: 'MTH 205',
    title: 'Math-III: Differential Equations & Probability',
    credits: 3,
    contactHours: 3,
  },
  {
    sl: 9,
    code: 'MTH 207',
    title: 'Math-IV: Applied Mathematics for Engineers',
    credits: 3,
    contactHours: 3,
  },
];

export const cseOtherEngineeringCourses: Course[] = [
  {
    sl: 1,
    code: 'EEE 101',
    title: 'Introduction to Electrical Engineering',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 2,
    code: 'EEE 102',
    title: 'Introduction to Electrical Engineering Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 3,
    code: 'EEE 103',
    title: 'Electronic Devices and Circuits',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 4,
    code: 'EEE 104',
    title: 'Electronic Devices and Circuits Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 5,
    code: 'EEE 201',
    title: 'Electrical Drives and Instrumentation',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 6,
    code: 'EEE 202',
    title: 'Electrical Drives and Instrumentation Sessional',
    credits: 1.5,
    contactHours: 0,
  },
  {
    sl: 7,
    code: 'CE-100',
    title: 'Engineering Drawing and CAD Sessional',
    credits: 1.5,
    contactHours: 0,
  },
];

export const cseIndustrialCourses: Course[] = [
  {
    sl: 1,
    code: 'CSE 440',
    title: 'Industrial Training (Internship)',
    credits: 3,
    contactHours: 0,
  },
];

export const cseProjectCourses: Course[] = [
  {
    sl: 1,
    code: 'CSE 400',
    title: 'Project',
    credits: 3,
    contactHours: 0,
  },
  {
    sl: 2,
    code: 'CSE 430',
    title: 'Thesis',
    credits: 3,
    contactHours: 0,
  },
];

export const cseElectiveCourses: ElectiveCourseGroup[] = [
  {
    title: 'Option I (Any Two, 6.00 Credits)',
    courses: [
      {
        sl: 1,
        code: 'CSE 337',
        title: 'Simulation and Modeling',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 2,
        code: 'CSE 338',
        title: 'Simulation and Modeling Sessional',
        credits: 1.5,
        contactHours: 0,
      },
      {
        sl: 3,
        code: 'CSE 339',
        title: 'Multimedia Systems Design',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 4,
        code: 'CSE 340',
        title: 'Multimedia Systems Design Sessional',
        credits: 1.5,
        contactHours: 0,
      },
      {
        sl: 5,
        code: 'CSE 341',
        title: 'VLSI Design',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 6,
        code: 'CSE 342',
        title: 'VLSI Design Sessional',
        credits: 1.5,
        contactHours: 0,
      },
      {
        sl: 7,
        code: 'CSE 343',
        title: 'Advance Object Oriented Programming',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 8,
        code: 'CSE 344',
        title: 'Advance Object Oriented Programming Sessional',
        credits: 1.5,
        contactHours: 0,
      },
    ],
  },
  {
    title: 'Option II [Any Three (Course with Sessional), 9.00 Credits]',
    courses: [
      {
        sl: 1,
        code: 'CSE 421',
        title: 'Optical Fiber Communication',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 2,
        code: 'CSE 447',
        title: 'Network Security',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 3,
        code: 'CSE 427',
        title: 'E-Commerce',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 4,
        code: 'CSE 441',
        title: 'Advanced DBMS',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 5,
        code: 'CSE 429',
        title: 'Web Programming',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 6,
        code: 'CSE 423',
        title: 'Mobile Cellular Communication',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 7,
        code: 'CSE 425',
        title: 'Wireless Communication',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 8,
        code: 'CSE 443',
        title: 'Advance Network Services and Management',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 9,
        code: 'CSE 445',
        title: 'Mobile Computing',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 10,
        code: 'CSE 449',
        title: 'Embedded Systems',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 11,
        code: 'CSE 451',
        title: 'Mobile Application Development',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 12,
        code: 'CSE 453',
        title: 'Digital Image Processing',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 13,
        code: 'CSE 455',
        title: 'Game Design & Development',
        credits: 3,
        contactHours: 0,
      },
      {
        sl: 14,
        code: 'CSE 457',
        title: 'Cloud Computing',
        credits: 3,
        contactHours: 0,
      },
    ],
  },
];

export const cseCoursePrefixes: CoursePrefix[] = [
  { symbol: 'CE', name: 'cse Engineering' },
  { symbol: 'CHM', name: 'Chemistry' },
  { symbol: 'EEE', name: 'Electrical and Electronics Engineering' },
  { symbol: 'ENG', name: 'English' },
  { symbol: 'HUM', name: 'Humanities and Social Sciences' },
  { symbol: 'MTH', name: 'Mathematics' },
  { symbol: 'PHY', name: 'Physics' },
];

export const cseCurriculumSummary: CurriculumSummary[] = [
  {
    category: 'General Education',
    theory_courses: 5,
    sessional_courses: 1,
    credits: 12,
  },
  {
    category: 'Basic Science and Mathematics',
    theory_courses: 7,
    sessional_courses: 2,
    credits: 23,
  },
  {
    category: 'Other Engineering Disciplines',
    theory_courses: 1,
    sessional_courses: 0,
    credits: 3,
  },
  {
    category: 'CE Core',
    theory_courses: 28,
    sessional_courses: 19,
    credits: 112,
  },
  {
    category: 'Elective',
    theory_courses: 4,
    sessional_courses: 3,
    credits: 15,
  },
];

// The semester data is unchanged from the previous correct version and is omitted here for brevity.
// cseRegularSemesterData and cseEveningSemesterData should be included here in the final file.

// Semester Data remains the same as the previously corrected version...
// HSC Background Students - Regular Program
export const cseRegularSemesterData: Semester[] = [
  {
    year: 1,
    semester: 1,
    title: '1st Year 1st Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'PHY-101',
        courseTitle: 'Physics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'PHY-102',
        courseTitle: 'Physics Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 3,
        courseCode: 'CHM-101',
        courseTitle: 'Chemistry',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'ENG-101',
        courseTitle: 'Foundation English',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'MTH-101',
        courseTitle: 'Mathematics-I (Differential and Integral Calculus)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'CSE-100',
        courseTitle: 'Introduction to Computer Systems',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 16.5,
    contactHours: 16.5,
  },
  {
    year: 1,
    semester: 2,
    title: '1st Year 2nd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'MTH-103',
        courseTitle:
          'Mathematics-II (Ordinary and Partial Differential Equations)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE-121',
        courseTitle: 'Structured Programming Language',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'CSE-122',
        courseTitle: 'Structured Programming Language Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 4,
        courseCode: 'CSE-123',
        courseTitle: 'Discrete Mathematics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-101',
        courseTitle: 'Introduction to Electrical Engineering',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-102',
        courseTitle: 'Introduction to Electrical Engineering Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 15,
    contactHours: 15,
  },
  {
    year: 1,
    semester: 3,
    title: '1st Year 3rd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'MTH-105',
        courseTitle:
          'Mathematics-III (Matrices, Vector Analysis and Fourier Series)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE-131',
        courseTitle: 'Data Structures',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'CSE-132',
        courseTitle: 'Data Structures Lab',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 4,
        courseCode: 'CSE-133',
        courseTitle: 'Numerical Methods',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-103',
        courseTitle: 'Electronics Device and Circuits',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-104',
        courseTitle: 'Electronics Device and Circuits Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 15,
    contactHours: 15,
  },
  {
    year: 2,
    semester: 1,
    title: '2nd Year 1st Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'MTH-207',
        courseTitle: 'Mathematics-IV (Complex Variable and Laplace Transform)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE-211',
        courseTitle: 'Object Oriented Programming Language',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'CSE-212',
        courseTitle: 'Object Oriented Programming Language Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 4,
        courseCode: 'EEE-201',
        courseTitle: 'Electrical Drives and Instrumentation',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-202',
        courseTitle: 'Electrical Drives and Instrumentation Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 6,
        courseCode: 'CSE-213',
        courseTitle: 'Digital Logic Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 7,
        courseCode: 'CSE-214',
        courseTitle: 'Digital Logic Design Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 16.5,
    contactHours: 16.5,
  },
  {
    year: 2,
    semester: 2,
    title: '2nd Year 2nd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'ACT-201',
        courseTitle: 'Financial & Managerial Accounting',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'MTH-221',
        courseTitle: 'Mathematics-V (Statistics and Coordinate Geometry)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'CSE-221',
        courseTitle: 'Algorithms',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CSE-222',
        courseTitle: 'Algorithms Lab',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 5,
        courseCode: 'CSE-223',
        courseTitle: 'Database Management Systems',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'CSE-224',
        courseTitle: 'Database Management Systems Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 15,
    contactHours: 15,
  },
  {
    year: 2,
    semester: 3,
    title: '2nd Year 3rd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'CSE-231',
        courseTitle: 'Operating Systems',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE-232',
        courseTitle: 'Operating Systems Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 3,
        courseCode: 'CSE-233',
        courseTitle: 'System Analysis and Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CSE-234',
        courseTitle: 'System Analysis and Design Lab',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 5,
        courseCode: 'CSE-235',
        courseTitle: 'Computer Architecture',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'CSE-236',
        courseTitle: 'Assembly Language Programming Sessional',
        credit: 1,
        contactHours: 1,
      },
    ],
    total: 13,
    contactHours: 13,
  },
  {
    year: 3,
    semester: 1,
    title: '3rd Year 1st Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'CSE-315',
        courseTitle: 'Theory of Computing',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE-311',
        courseTitle: 'Artificial Intelligence',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'CSE-312',
        courseTitle: 'Artificial Intelligence Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 4,
        courseCode: 'CSE-317',
        courseTitle: 'Data Communication',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'CSE-313',
        courseTitle: 'Microprocessor and Microcontroller',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'CSE-314',
        courseTitle: 'Microprocessor and Microcontroller Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 15,
    contactHours: 15,
  },
  {
    year: 3,
    semester: 2,
    title: '3rd Year 2nd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'CSE-323',
        courseTitle: 'Compiler',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 2,
        courseCode: 'CSE-324',
        courseTitle: 'Compiler Lab',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 3,
        courseCode: 'CSE-321',
        courseTitle: 'Software Engineering',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 4,
        courseCode: 'CSE-322',
        courseTitle: 'Software Engineering Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 5,
        courseCode: 'CSE-325',
        courseTitle: 'Digital System Design',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 6,
        courseCode: 'CSE-326',
        courseTitle: 'Digital System Design Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 13.5,
    contactHours: 13.5,
  },
  {
    year: 3,
    semester: 3,
    title: '3rd Year 3rd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'CSE-331',
        courseTitle: 'Computer Network',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 2,
        courseCode: 'CSE-332',
        courseTitle: 'Computer Networks Lab',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 3,
        courseCode: 'CSE-333',
        courseTitle: 'Pattern Recognition',
        credit: 9.0,
        contactHours: 9.0,
      },
      {
        slNo: 4,
        courseCode: 'CSE-334',
        courseTitle: 'Pattern Recognition Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 5,
        courseCode: 'CSE-335',
        courseTitle: 'Computer Graphics',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 6,
        courseCode: 'CSE-336',
        courseTitle: 'Computer Graphics Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 7,
        courseCode: 'CSE-337',
        courseTitle: 'Simulation & Modeling',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 8,
        courseCode: 'CSE-338',
        courseTitle: 'Simulation & Modeling Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 9,
        courseCode: 'CSE-339',
        courseTitle: 'Multimedia Systems Design',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 10,
        courseCode: 'CSE-340',
        courseTitle: 'Multimedia Systems Design Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 11,
        courseCode: 'CSE-341',
        courseTitle: 'VLSI Design',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 12,
        courseCode: 'CSE-342',
        courseTitle: 'VLSI Design Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 13,
        courseCode: 'CSE-343',
        courseTitle: 'Advanced Object Oriented Programming',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 14,
        courseCode: 'CSE-344',
        courseTitle: 'Advanced Object Oriented Programming Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
    ],
    total: 13.5,
    contactHours: 13.5,
  },
  {
    year: 4,
    semester: 1,
    title: '4th Year 1st Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'ECO-201',
        courseTitle: 'Engineering Economics',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 2,
        courseCode: 'CSE-417',
        courseTitle: 'Project Management',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 3,
        courseCode: 'CSE-400',
        courseTitle: 'Project & Thesis',
        credit: 3.0,
        contactHours: 3.0,
      },
    ],
    total: 9.0,
    contactHours: 9.0,
  },
  {
    year: 4,
    semester: 2,
    title: '4th Year 2nd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'MGT-201',
        courseTitle: 'Industrial and Operational Management',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 2,
        courseCode: 'CSE-421',
        courseTitle: 'Optical Fiber Communication',
        credit: 9.0,
        contactHours: 9.0,
      },
      {
        slNo: 3,
        courseCode: 'CSE-423',
        courseTitle: 'Mobile Cellular Communication',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 4,
        courseCode: 'CSE-425',
        courseTitle: 'Wireless Communication',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 5,
        courseCode: 'CSE-427',
        courseTitle: 'E-Commerce',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 6,
        courseCode: 'CSE-429',
        courseTitle: 'Web Programming',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 7,
        courseCode: 'CSE-441',
        courseTitle: 'Advanced DBMS',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 8,
        courseCode: 'CSE-443',
        courseTitle: 'Advanced Network Services and Management',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 9,
        courseCode: 'CSE-445',
        courseTitle: 'Mobile Computing',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 10,
        courseCode: 'CSE-447',
        courseTitle: 'Network Security',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 11,
        courseCode: 'CSE-449',
        courseTitle: 'Embedded Systems',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 12,
        courseCode: 'CSE-451',
        courseTitle: 'Mobile Application Development',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 13,
        courseCode: 'CSE-453',
        courseTitle: 'Digital Image Processing',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 14,
        courseCode: 'CSE-455',
        courseTitle: 'Game Design & Development',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 15,
        courseCode: 'CSE-457',
        courseTitle: 'Cloud Computing',
        credit: 0.0,
        contactHours: 0.0,
      },
    ],
    total: 12.0,
    contactHours: 12.0,
  },
  {
    year: 4,
    semester: 3,
    title: '4th Year 3rd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'CSE-430',
        courseTitle: 'Project & Thesis',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 2,
        courseCode: 'CSE-440',
        courseTitle: 'Industrial Training',
        credit: 3.0,
        contactHours: 3.0,
      },
    ],
    total: 6.0,
    contactHours: 6.0,
  },
];

// Diploma Background Students - Evening Program
export const cseEveningSemesterData: Semester[] = [
  {
    year: 1,
    semester: 1,
    title: '1st Year 1st Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'PHY-101',
        courseTitle: 'Physics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'PHY-102',
        courseTitle: 'Physics Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 3,
        courseCode: 'CHM-101',
        courseTitle: 'Chemistry',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'ENG-101',
        courseTitle: 'Foundation English',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'MTH-101',
        courseTitle: 'Mathematics-I (Differential and Integral Calculus)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'CSE-100',
        courseTitle: 'Introduction to Computer Systems',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 16.5,
    contactHours: 16.5,
  },
  {
    year: 1,
    semester: 2,
    title: '1st Year 2nd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'MTH-103',
        courseTitle:
          'Mathematics-II (Ordinary and Partial Differential Equations)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE-121',
        courseTitle: 'Structured Programming Language',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'CSE-122',
        courseTitle: 'Structured Programming Language Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 4,
        courseCode: 'CSE-123',
        courseTitle: 'Discrete Mathematics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-101',
        courseTitle: 'Introduction to Electrical Engineering',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-102',
        courseTitle: 'Introduction to Electrical Engineering Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 15,
    contactHours: 15,
  },
  {
    year: 1,
    semester: 3,
    title: '1st Year 3rd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'MTH-105',
        courseTitle:
          'Mathematics-III (Matrices, Vector Analysis and Fourier Series)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE-131',
        courseTitle: 'Data Structures',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'CSE-132',
        courseTitle: 'Data Structures Lab',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 4,
        courseCode: 'CSE-133',
        courseTitle: 'Numerical Methods',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-103',
        courseTitle: 'Electronics Device and Circuits',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-104',
        courseTitle: 'Electronics Device and Circuits Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 15,
    contactHours: 15,
  },
  {
    year: 2,
    semester: 1,
    title: '2nd Year 1st Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'MTH-207',
        courseTitle: 'Mathematics-IV (Complex Variable and Laplace Transform)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE-211',
        courseTitle: 'Object Oriented Programming Language',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'CSE-212',
        courseTitle: 'Object Oriented Programming Language Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 4,
        courseCode: 'EEE-201',
        courseTitle: 'Electrical Drives and Instrumentation',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-202',
        courseTitle: 'Electrical Drives and Instrumentation Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 6,
        courseCode: 'CSE-213',
        courseTitle: 'Digital Logic Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 7,
        courseCode: 'CSE-214',
        courseTitle: 'Digital Logic Design Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 16.5,
    contactHours: 16.5,
  },
  {
    year: 2,
    semester: 2,
    title: '2nd Year 2nd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'ACT-201',
        courseTitle: 'Financial & Managerial Accounting',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'MTH-221',
        courseTitle: 'Mathematics-V (Statistics and Coordinate Geometry)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'CSE-221',
        courseTitle: 'Algorithms',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CSE-222',
        courseTitle: 'Algorithms Lab',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 5,
        courseCode: 'CSE-223',
        courseTitle: 'Database Management Systems',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'CSE-224',
        courseTitle: 'Database Management Systems Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 15,
    contactHours: 15,
  },
  {
    year: 2,
    semester: 3,
    title: '2nd Year 3rd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'CSE-231',
        courseTitle: 'Operating Systems',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE-232',
        courseTitle: 'Operating Systems Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 3,
        courseCode: 'CSE-233',
        courseTitle: 'System Analysis and Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CSE-234',
        courseTitle: 'System Analysis and Design Lab',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 5,
        courseCode: 'CSE-235',
        courseTitle: 'Computer Architecture',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'CSE-236',
        courseTitle: 'Assembly Language Programming Sessional',
        credit: 1,
        contactHours: 1,
      },
    ],
    total: 13,
    contactHours: 13,
  },
  {
    year: 3,
    semester: 1,
    title: '3rd Year 1st Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'CSE-315',
        courseTitle: 'Theory of Computing',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE-311',
        courseTitle: 'Artificial Intelligence',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'CSE-312',
        courseTitle: 'Artificial Intelligence Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 4,
        courseCode: 'CSE-317',
        courseTitle: 'Data Communication',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'CSE-313',
        courseTitle: 'Microprocessor and Microcontroller',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'CSE-314',
        courseTitle: 'Microprocessor and Microcontroller Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 15,
    contactHours: 15,
  },
  {
    year: 3,
    semester: 2,
    title: '3rd Year 2nd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'CSE-323',
        courseTitle: 'Compiler',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 2,
        courseCode: 'CSE-324',
        courseTitle: 'Compiler Lab',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 3,
        courseCode: 'CSE-321',
        courseTitle: 'Software Engineering',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 4,
        courseCode: 'CSE-322',
        courseTitle: 'Software Engineering Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 5,
        courseCode: 'CSE-325',
        courseTitle: 'Digital System Design',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 6,
        courseCode: 'CSE-326',
        courseTitle: 'Digital System Design Sessional',
        credit: 1.5,
        contactHours: 1.5,
      },
    ],
    total: 13.5,
    contactHours: 13.5,
  },
  {
    year: 3,
    semester: 3,
    title: '3rd Year 3rd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'CSE-331',
        courseTitle: 'Computer Network',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 2,
        courseCode: 'CSE-332',
        courseTitle: 'Computer Networks Lab',
        credit: 1.5,
        contactHours: 1.5,
      },
      {
        slNo: 3,
        courseCode: 'CSE-333',
        courseTitle: 'Pattern Recognition',
        credit: 9.0,
        contactHours: 9.0,
      },
      {
        slNo: 4,
        courseCode: 'CSE-334',
        courseTitle: 'Pattern Recognition Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 5,
        courseCode: 'CSE-335',
        courseTitle: 'Computer Graphics',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 6,
        courseCode: 'CSE-336',
        courseTitle: 'Computer Graphics Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 7,
        courseCode: 'CSE-337',
        courseTitle: 'Simulation & Modeling',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 8,
        courseCode: 'CSE-338',
        courseTitle: 'Simulation & Modeling Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 9,
        courseCode: 'CSE-339',
        courseTitle: 'Multimedia Systems Design',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 10,
        courseCode: 'CSE-340',
        courseTitle: 'Multimedia Systems Design Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 11,
        courseCode: 'CSE-341',
        courseTitle: 'VLSI Design',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 12,
        courseCode: 'CSE-342',
        courseTitle: 'VLSI Design Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 13,
        courseCode: 'CSE-343',
        courseTitle: 'Advanced Object Oriented Programming',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 14,
        courseCode: 'CSE-344',
        courseTitle: 'Advanced Object Oriented Programming Sessional',
        credit: 0.0,
        contactHours: 0.0,
      },
    ],
    total: 13.5,
    contactHours: 13.5,
  },
  {
    year: 4,
    semester: 1,
    title: '4th Year 1st Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'ECO-201',
        courseTitle: 'Engineering Economics',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 2,
        courseCode: 'CSE-417',
        courseTitle: 'Project Management',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 3,
        courseCode: 'CSE-400',
        courseTitle: 'Project & Thesis',
        credit: 3.0,
        contactHours: 3.0,
      },
    ],
    total: 9.0,
    contactHours: 9.0,
  },
  {
    year: 4,
    semester: 2,
    title: '4th Year 2nd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'MGT-201',
        courseTitle: 'Industrial and Operational Management',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 2,
        courseCode: 'CSE-421',
        courseTitle: 'Optical Fiber Communication',
        credit: 9.0,
        contactHours: 9.0,
      },
      {
        slNo: 3,
        courseCode: 'CSE-423',
        courseTitle: 'Mobile Cellular Communication',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 4,
        courseCode: 'CSE-425',
        courseTitle: 'Wireless Communication',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 5,
        courseCode: 'CSE-427',
        courseTitle: 'E-Commerce',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 6,
        courseCode: 'CSE-429',
        courseTitle: 'Web Programming',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 7,
        courseCode: 'CSE-441',
        courseTitle: 'Advanced DBMS',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 8,
        courseCode: 'CSE-443',
        courseTitle: 'Advanced Network Services and Management',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 9,
        courseCode: 'CSE-445',
        courseTitle: 'Mobile Computing',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 10,
        courseCode: 'CSE-447',
        courseTitle: 'Network Security',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 11,
        courseCode: 'CSE-449',
        courseTitle: 'Embedded Systems',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 12,
        courseCode: 'CSE-451',
        courseTitle: 'Mobile Application Development',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 13,
        courseCode: 'CSE-453',
        courseTitle: 'Digital Image Processing',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 14,
        courseCode: 'CSE-455',
        courseTitle: 'Game Design & Development',
        credit: 0.0,
        contactHours: 0.0,
      },
      {
        slNo: 15,
        courseCode: 'CSE-457',
        courseTitle: 'Cloud Computing',
        credit: 0.0,
        contactHours: 0.0,
      },
    ],
    total: 12.0,
    contactHours: 12.0,
  },
  {
    year: 4,
    semester: 3,
    title: '4th Year 3rd Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'CSE-430',
        courseTitle: 'Project & Thesis',
        credit: 3.0,
        contactHours: 3.0,
      },
      {
        slNo: 2,
        courseCode: 'CSE-440',
        courseTitle: 'Industrial Training',
        credit: 3.0,
        contactHours: 3.0,
      },
    ],
    total: 6.0,
    contactHours: 6.0,
  },
];
