import type {
  Course,
  CoursePrefix,
  CurriculumSummary,
  PerformanceEvaluation,
  ProgramDetails,
  Semester,
} from '@/app/programs/_config/curriculum';

export const eeeSemesterInfo = {
  spring: 'January-April',
  summer: 'May-August',
  fall: 'September-December',
};

export const eeeRegularProgramDetails: ProgramDetails = {
  degreeName:
    'Bachelor of Science in Electrical and Electronic Engineering (B.Sc. in EEE)',
  duration: {
    years: 4,
    semesters: 12,
  },
  creditHours: 160,
  courseLoad: '16 Weeks/Semester',
  courseLoadDetails:
    'Classes and continuous assessments: 12 weeks, Mid Term and Semester Final Examinations: 4 weeks',
  minimumGPA: 2.2,
  backgroundStudents: 'For HSC Passed Students',
};

export const eeeEveningProgramDetails: ProgramDetails = {
  degreeName:
    'Bachelor of Science in Electrical and Electronic Engineering (B.Sc. in EEE)',
  duration: {
    years: '3 years, 4 months',
    semesters: 10,
  },
  creditHours: '160 (142 + 18 waived)',
  courseLoad: '16 Weeks/Semester',
  courseLoadDetails:
    'Classes and continuous assessments: 12 weeks, Mid Term and Semester Final Examinations: 4 weeks',
  minimumGPA: 2.2,
  backgroundStudents: 'For Diploma in Engineering Passed Students',
  waiverInfo:
    'The first two (02) semesters, totaling 18.00 credits, are waived for Evening batch students who have completed a diploma in engineering degree.',
};

export const eeePerformanceEvaluation: PerformanceEvaluation[] = [
  {
    category: '(a) Theory Courses:',
    criteria: [
      { item: 'Class Participation (Attendance)', percentage: '20%' },
      {
        item: 'Continuous Assessment (Class Tests, Assignments, Presentations etc.)',
        percentage: '20%',
      },
      { item: 'Mid Term Examination', percentage: '30%' },
      { item: 'Semester Final Examination', percentage: '30%' },
    ],
  },
  {
    category: '(b) Courses on Laboratory/Sessional/Field Work:',
    criteria: [
      { item: 'Class Participation (Attendance)', percentage: '20%' },
      { item: 'Quiz', percentage: '20%' },
      { item: 'Viva Voce', percentage: '20%' },
      { item: 'Performance/Reports', percentage: '40%' },
    ],
  },
  {
    category: '(c) Project/Thesis:',
    criteria: [
      { item: 'Book', percentage: '10%' },
      { item: 'Presentation and Viva-Voce', percentage: '20%' },
      { item: 'Committee', percentage: '20%' },
      { item: 'Supervisor', percentage: '50%' },
    ],
  },
];

// * used
export const eeeCoreCoursesData: Course[] = [
  {
    sl: 1,
    code: 'ME 101',
    title: 'Introduction to Mechanical Engineering',
    credits: 3,
  },
  {
    sl: 2,
    code: 'ME 160',
    title: 'Mechanical Engineering Drawing - I',
    credits: 1.5,
  },
  { sl: 3, code: 'Shop 160', title: 'Foundry and Welding Shops', credits: 1.5 },
  { sl: 4, code: 'ME 171', title: 'Computer Programming Language', credits: 3 },
  {
    sl: 5,
    code: 'ME 172',
    title: 'Computer Programming Language Sessional',
    credits: 0.75,
  },
  { sl: 6, code: 'SHOP 170', title: 'Machine Shop Practice', credits: 1.5 },
  { sl: 7, code: 'ME 203', title: 'Engineering Thermodynamics', credits: 3 },
  {
    sl: 8,
    code: 'ME 204',
    title: 'Engineering Thermodynamics Sessional',
    credits: 0.75,
  },
  { sl: 9, code: 'ME 247', title: 'Engineering Mechanics-I', credits: 3 },
  { sl: 10, code: 'ME 243', title: 'Mechanics of Solids', credits: 3 },
  {
    sl: 11,
    code: 'ME 244',
    title: 'Mechanics of Solids Sessional',
    credits: 0.75,
  },
  {
    sl: 12,
    code: 'ME 260',
    title: 'Mechanical Engineering Drawing-II',
    credits: 1.5,
  },
  { sl: 13, code: 'ME 261', title: 'Numerical Analysis', credits: 3 },
  {
    sl: 14,
    code: 'ME 262',
    title: 'Numerical Analysis Sessional',
    credits: 0.75,
  },
  { sl: 15, code: 'ME 249', title: 'Engineering Mechanics-II', credits: 3 },
  { sl: 16, code: 'ME 305', title: 'Heat Transfer', credits: 3 },
  { sl: 17, code: 'ME 306', title: 'Heat Transfer Sessional', credits: 0.75 },
  { sl: 18, code: 'ME 321', title: 'Fluid Mechanics - I', credits: 3 },
  { sl: 19, code: 'ME 349', title: 'Mechanics of Machinery', credits: 3 },
  {
    sl: 20,
    code: 'ME 350',
    title: 'Mechanics of Machinery Sessional',
    credits: 1.5,
  },
  {
    sl: 21,
    code: 'ME 361',
    title: 'Instrumentation and Measurement',
    credits: 3,
  },
  {
    sl: 22,
    code: 'ME 366',
    title: 'Electro-Mechanical System Design and Practice',
    credits: 1.5,
  },
  {
    sl: 23,
    code: 'ME 307',
    title: 'Heat Transfer Equipment Design',
    credits: 3,
  },
  { sl: 24, code: 'ME 310', title: 'Thermo-Fluid System Design', credits: 1.5 },
  { sl: 25, code: 'ME 323', title: 'Fluid Mechanics-II', credits: 3 },
  { sl: 26, code: 'ME 326', title: 'Fluid Mechanics Sessional', credits: 0.75 },
  { sl: 27, code: 'ME 351', title: 'Machine Design', credits: 4 },
  { sl: 28, code: 'ME 352', title: 'Machine Design Sessional', credits: 1.5 },
  { sl: 29, code: 'ME 417', title: 'Internal Combustion Engines', credits: 3 },
  { sl: 30, code: 'ME 418', title: 'Heat Engines Sessional', credits: 0.75 },
  { sl: 31, code: 'ME 421', title: 'Fluid Machinery', credits: 3 },
  { sl: 32, code: 'ME 422', title: 'Fluid Machinery Sessional', credits: 0.75 },
  { sl: 33, code: 'ME 400', title: 'Project and Thesis', credits: 3 },
  { sl: 34, code: 'ME 419', title: 'Power Plant Engineering', credits: 3 },
  {
    sl: 35,
    code: 'ME 420',
    title: 'Power Plant Engineering Sessional',
    credits: 0.75,
  },
];

export const eeeElectiveCourses: Course[] = [
  { sl: 1, code: 'ME 407', title: 'Advanced Thermodynamics', credits: 3 },
  { sl: 2, code: 'ME 409', title: 'Renewable Energy', credits: 3 },
  { sl: 3, code: 'ME 411', title: 'Combustion and Pollution', credits: 3 },
  { sl: 4, code: 'ME 413', title: 'Energy and Environment', credits: 3 },
  {
    sl: 5,
    code: 'ME 415',
    title: 'Refrigeration and Building Mechanical System',
    credits: 3,
  },
  { sl: 6, code: 'ME 423', title: 'Fluids Engineering', credits: 3 },
  { sl: 7, code: 'ME 425', title: 'Aerodynamics', credits: 3 },
  {
    sl: 8,
    code: 'ME 427',
    title: 'Applied Engineering Mathematics',
    credits: 3,
  },
  {
    sl: 9,
    code: 'ME 429',
    title: 'Similitude in Engineering Mechanics',
    credits: 3,
  },
  { sl: 10, code: 'ME 431', title: 'Gas Dynamics', credits: 3 },
  { sl: 11, code: 'ME 433', title: 'Fluidics', credits: 3 },
  { sl: 12, code: 'ME 437', title: 'Design of Fluid Machines', credits: 3 },
  { sl: 13, code: 'ME 439', title: 'Biomedical Fluid Mechanics', credits: 3 },
  { sl: 14, code: 'ME 441', title: 'Theory of Structures', credits: 3 },
  { sl: 15, code: 'ME 445', title: 'Noise and Vibration', credits: 3 },
  { sl: 16, code: 'ME 447', title: 'Robotics', credits: 3 },
  { sl: 17, code: 'ME 449', title: 'Composite Materials', credits: 3 },
  { sl: 18, code: 'ME 461', title: 'Control Engineering', credits: 3 },
  { sl: 19, code: 'ME 463', title: 'Petroleum Engineering', credits: 3 },
  { sl: 20, code: 'ME 465', title: 'Applied Statistics', credits: 3 },
  { sl: 21, code: 'ME 467', title: 'Automobile Engineering', credits: 3 },
  { sl: 22, code: 'ME 469', title: 'Nuclear Engineering', credits: 3 },
  { sl: 23, code: 'ME 471', title: 'Bio-Engineering', credits: 3 },
  { sl: 24, code: 'ME 473', title: 'Plastics Process Technology', credits: 3 },
  { sl: 25, code: 'ME 475', title: 'Mechatronics', credits: 3 },
  { sl: 26, code: 'ME 481', title: 'Textile Technology', credits: 3 },
];

export const eeeElectiveCoursesIPE: Course[] = [
  {
    sl: 1,
    code: 'IPE 435',
    title: 'Modern Manufacturing Technology',
    credits: 3,
  },
  { sl: 2, code: 'IPE 433', title: 'Metal Cutting Processes', credits: 3 },
  { sl: 3, code: 'IPE 437', title: 'CAD/CAM', credits: 3 },
  {
    sl: 4,
    code: 'IPE 483',
    title: 'Production Planning and Control',
    credits: 3,
  },
  { sl: 5, code: 'IPE 485', title: 'Operations Research', credits: 3 },
  { sl: 6, code: 'IPE 487', title: 'Material Handling', credits: 3 },
];

export const eeeCoursePrefixes: CoursePrefix[] = [
  { symbol: 'ACT', name: 'Business Administration' },
  { symbol: 'GED', name: 'General Education Development' },
  { symbol: 'CHM', name: 'Chemistry' },
  { symbol: 'ECO', name: 'Economics' },
  { symbol: 'ME', name: 'Mechanical Engineering' },
  { symbol: 'CSE', name: 'Computer Science and Engineering' },
  { symbol: 'MTH', name: 'Mathematics' },
  { symbol: 'EEE', name: 'Electrical and Electronic Engineering' },
  { symbol: 'PHY', name: 'Physics' },
  { symbol: 'ENG', name: 'English' },
  { symbol: 'HSS', name: 'Humanities and Social Science' },
  { symbol: 'IDE', name: 'Interdisciplinary Engineering' },
  { symbol: 'CE', name: 'Civil Engineering' },
  { symbol: 'MGT', name: 'Management' },
];
// * ///////////

export const eeeGeneralEducationCourses: Course[] = [
  {
    sl: 1,
    code: 'GED-101',
    title: 'Bangladesh Studies (History of Independence of Bangladesh)',
    credits: 3,
  },
  { sl: 2, code: 'ENG-101', title: 'Oral and Written English', credits: 3 },
  {
    sl: 3,
    code: 'BBA-103',
    title: 'Financial & Managerial Accounting',
    credits: 3,
  },
  { sl: 4, code: 'GED-103', title: 'Introduction to Sociology', credits: 3 },
  { sl: 5, code: 'BBA-201', title: 'Business Communication', credits: 3 },
  {
    sl: 6,
    code: 'BBA-207',
    title: 'Industrial and Operational Management',
    credits: 3,
  },
  { sl: 7, code: 'GED-301', title: 'Professional Ethics', credits: 3 },
  { sl: 8, code: 'BBA-313', title: 'Industrial Economics', credits: 3 },
];

export const eeeBasicScienceCourses: Course[] = [
  { sl: 1, code: 'PHY-101', title: 'Physics-I', credits: 3 },
  { sl: 2, code: 'PHY-102', title: 'Physics-I Lab', credits: 1 },
  { sl: 3, code: 'PHY-103', title: 'Physics-II', credits: 3 },
  { sl: 4, code: 'PHY-104', title: 'Physics-II Lab', credits: 1 },
  { sl: 5, code: 'CHM-101', title: 'Chemistry', credits: 3 },
  { sl: 6, code: 'CHM-102', title: 'Chemistry Lab', credits: 1 },
  {
    sl: 7,
    code: 'MTH-101',
    title: 'Differential and Integral Calculus',
    credits: 3,
  },
  { sl: 8, code: 'MTH-103', title: 'Differential Equations', credits: 3 },
  {
    sl: 9,
    code: 'MTH-201',
    title: 'Linear Algebra and Complex Variable',
    credits: 3,
  },
  {
    sl: 10,
    code: 'MTH-203',
    title: 'Probability and Statistics',
    credits: 3,
  },
  {
    sl: 11,
    code: 'MTH-205',
    title: 'Co-ordinate Geometry and Vector Analysis',
    credits: 3,
  },
  {
    sl: 12,
    code: 'MTH-301',
    title: 'Numerical Methods and Fourier and Laplace Transformation',
    credits: 3,
  },
];

export const eeeInterDisciplinaryCourses: Course[] = [
  { sl: 1, code: 'CSE-203', title: 'Programming Language', credits: 3 },
  { sl: 2, code: 'CSE-204', title: 'Programming Language Lab', credits: 1 },
  {
    sl: 3,
    code: 'ME-201',
    title: 'Mechanical Engineering Fundamentals',
    credits: 3,
  },
  { sl: 4, code: 'EEE-285', title: 'Biomedical Electronics', credits: 3 },
];

export const eeeProjectCourses: Course[] = [
  { sl: 1, code: 'EEE-498', title: 'Project/Thesis', credits: 6 },
];

export const eeeCurriculumSummary: CurriculumSummary[] = [
  {
    category: 'Core Courses',
    credits: 87,
  },
  {
    category: 'Elective Courses',
    credits: 15,
  },
  {
    category: 'Basic Science and Mathematics Courses',
    credits: 30,
  },
  {
    category: 'General Education Courses: English & Others',
    credits: 15,
  },
  {
    category: 'Inter-Disciplinary Engineering Courses',
    credits: 7,
  },
  {
    category: 'Project/Thesis',
    credits: 6,
  },
];

// HSC Background Students - Regular Program
export const eeeRegularSemesterData: Semester[] = [
  {
    year: 1,
    semester: 1,
    title: 'First Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-101',
        courseTitle: 'Electrical Circuits-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-102',
        courseTitle: 'Electrical Circuits-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'MTH-101',
        courseTitle: 'Differential and Integral Calculus',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CHM-101',
        courseTitle: 'Chemistry',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'CHM-102',
        courseTitle: 'Chemistry Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'PHY-101',
        courseTitle: 'Physics-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 7,
        courseCode: 'PHY-102',
        courseTitle: 'Physics-I Lab',
        credit: 1,
        contactHours: 2,
      },
    ],
    total: 15,
    contactHours: 18,
  },
  {
    year: 1,
    semester: 2,
    title: 'First Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-103',
        courseTitle: 'Electrical Circuits-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-104',
        courseTitle: 'Electrical Circuits-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'MTH-103',
        courseTitle: 'Differential Equations',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'PHY-103',
        courseTitle: 'Physics-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'PHY-104',
        courseTitle: 'Physics-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'ENG-101',
        courseTitle: 'Oral and Written English',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 1,
    semester: 3,
    title: 'First Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-201',
        courseTitle: 'Electronics-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-202',
        courseTitle: 'Electronics-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-100',
        courseTitle: 'Electrical Drawing and Drafting Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 4,
        courseCode: 'GED-101',
        courseTitle:
          'Bangladesh Studies (History of Independence of Bangladesh)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'BBA-103',
        courseTitle: 'Financial and Managerial Accounting',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-318',
        courseTitle: 'Engineering Simulation Lab',
        credit: 1,
        contactHours: 2,
      },
    ],
    total: 12,
    contactHours: 15,
  },
  {
    year: 2,
    semester: 1,
    title: 'Second Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-205',
        courseTitle: 'Electronics-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-206',
        courseTitle: 'Electronics-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'CSE-203',
        courseTitle: 'Programming Language',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CSE-204',
        courseTitle: 'Programming Language Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'MTH-201',
        courseTitle: 'Linear Algebra and Complex Variables',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'BBA-201',
        courseTitle: 'Business Communication',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 2,
    semester: 2,
    title: 'Second Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-203',
        courseTitle: 'Electrical Machines-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-204',
        courseTitle: 'Electrical Machines-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-211',
        courseTitle: 'Semiconductor Device',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'MTH-203',
        courseTitle: 'Probability and Statistics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'BBA-207',
        courseTitle: 'Industrial and Operational Management',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 13,
    contactHours: 14,
  },
  {
    year: 2,
    semester: 3,
    title: 'Second Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-207',
        courseTitle: 'Digital Logic Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-208',
        courseTitle: 'Digital Logic Design Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-209',
        courseTitle: 'Electrical Machines-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-210',
        courseTitle: 'Electrical Machines-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'ME-201',
        courseTitle: 'Mechanical Engineering Fundamentals',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'MTH-205',
        courseTitle: 'Co-ordinate Geometry and Vector Analysis',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 3,
    semester: 1,
    title: 'Third Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-301',
        courseTitle: 'Digital Electronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-302',
        courseTitle: 'Digital Electronics Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-303',
        courseTitle: 'Signals and Systems',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-304',
        courseTitle: 'Signals and Systems Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'EEE-311',
        courseTitle: 'Communication Engineering',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-312',
        courseTitle: 'Communication Engineering Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 7,
        courseCode: 'MTH-301',
        courseTitle: 'Numerical Methods and Fourier and Laplace Transformation',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 15,
    contactHours: 18,
  },
  {
    year: 3,
    semester: 2,
    title: 'Third Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-305',
        courseTitle: 'Electromagnetic Fields and Waves',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-309',
        courseTitle: 'Digital Signal Processing',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'EEE-310',
        courseTitle: 'Digital Signal Processing Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 4,
        courseCode: 'EEE-315',
        courseTitle: 'Electrical Measurements and Instrumentation',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-316',
        courseTitle: 'Electrical Measurements and Instrumentation Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'EEE-329',
        courseTitle: 'Electrical Machines-III',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 3,
    semester: 3,
    title: 'Third Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-307',
        courseTitle: 'Microprocessor and Interfacing',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-308',
        courseTitle: 'Microprocessor and Interfacing Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-345',
        courseTitle: 'Transmission and Distribution',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-347',
        courseTitle: 'Power Systems Engineering',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-449',
        courseTitle: 'Power Plant Engineering',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 13,
    contactHours: 14,
  },
  {
    year: 4,
    semester: 1,
    title: 'Fourth Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-401',
        courseTitle: 'Control Systems',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-402',
        courseTitle: 'Control Systems Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-413',
        courseTitle: 'Electrical Engineering Materials',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-463',
        courseTitle: 'VLSI Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-464',
        courseTitle: 'VLSI Design Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'EEE-471',
        courseTitle: 'Wireless and Mobile Communication',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 4,
    semester: 2,
    title: 'Fourth Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-431',
        courseTitle: 'Power Electronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-432',
        courseTitle: 'Power Electronics Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-453',
        courseTitle: 'Power System Protection',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-455',
        courseTitle: 'Renewable Energy',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-459',
        courseTitle: 'Optoelectronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-473',
        courseTitle: 'Optical Fiber Communications',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 16,
    contactHours: 17,
  },
  {
    year: 4,
    semester: 3,
    title: 'Fourth Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-498',
        courseTitle: 'Project/Thesis',
        credit: 6,
        contactHours: 6,
      },
    ],
    total: 6,
    contactHours: 6,
  },
];

// Diploma Background Students - Evening Program
export const eeeEveningSemesterData: Semester[] = [
  {
    year: 1,
    semester: 1,
    title: 'First Year, First Semester (Exempted)',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-101',
        courseTitle: 'Electrical Circuits-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-102',
        courseTitle: 'Electrical Circuits-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'MTH-101',
        courseTitle: 'Differential and Integral Calculus',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'BBA-103',
        courseTitle: 'Financial and Managerial Accounting',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 10,
    contactHours: 11,
    isExempted: true,
  },
  {
    year: 1,
    semester: 2,
    title: 'First Year, Second Semester (Exempted)',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-100',
        courseTitle: 'Electrical Drawing and Drafting Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 2,
        courseCode: 'PHY-101',
        courseTitle: 'Physics-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'PHY-102',
        courseTitle: 'Physics-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 4,
        courseCode: 'BBA-207',
        courseTitle: 'Industrial and Operational Management',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 8,
    contactHours: 10,
    isExempted: true,
  },
  {
    year: 1,
    semester: 3,
    title: 'First Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-103',
        courseTitle: 'Electrical Circuits-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-104',
        courseTitle: 'Electrical Circuits-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'MTH-103',
        courseTitle: 'Differential Equations',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CHM-101',
        courseTitle: 'Chemistry',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'CHM-102',
        courseTitle: 'Chemistry Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'PHY-103',
        courseTitle: 'Physics-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 7,
        courseCode: 'PHY-104',
        courseTitle: 'Physics-II Lab',
        credit: 1,
        contactHours: 2,
      },
    ],
    total: 15,
    contactHours: 18,
  },
  {
    year: 2,
    semester: 1,
    title: 'Second Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-201',
        courseTitle: 'Electronics-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-202',
        courseTitle: 'Electronics-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'CSE-203',
        courseTitle: 'Programming Language',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CSE-204',
        courseTitle: 'Programming Language Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'MTH-201',
        courseTitle: 'Linear Algebra and Complex Variables',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'ENG-101',
        courseTitle: 'Oral and Written English',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 7,
        courseCode: 'GED-101',
        courseTitle:
          'Bangladesh Studies (History of Independence of Bangladesh)',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 17,
    contactHours: 19,
  },
  {
    year: 2,
    semester: 2,
    title: 'Second Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-203',
        courseTitle: 'Electrical Machines-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-204',
        courseTitle: 'Electrical Machines-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-211',
        courseTitle: 'Semiconductor Device',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'ME-201',
        courseTitle: 'Mechanical Engineering Fundamentals',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'MTH-203',
        courseTitle: 'Probability and Statistics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'BBA-201',
        courseTitle: 'Business Communication',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 16,
    contactHours: 17,
  },
  {
    year: 2,
    semester: 3,
    title: 'Second Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-205',
        courseTitle: 'Electronics-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-206',
        courseTitle: 'Electronics-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-207',
        courseTitle: 'Digital Logic Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-208',
        courseTitle: 'Digital Logic Design Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'EEE-209',
        courseTitle: 'Electrical Machines-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-210',
        courseTitle: 'Electrical Machines-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 7,
        courseCode: 'MTH-205',
        courseTitle: 'Co-ordinate Geometry and Vector Analysis',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 15,
    contactHours: 18,
  },
  {
    year: 3,
    semester: 1,
    title: 'Third Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-301',
        courseTitle: 'Digital Electronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-302',
        courseTitle: 'Digital Electronics Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-303',
        courseTitle: 'Signals and Systems',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-304',
        courseTitle: 'Signals and Systems Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'EEE-311',
        courseTitle: 'Communication Engineering',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-312',
        courseTitle: 'Communication Engineering Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 7,
        courseCode: 'MTH-301',
        courseTitle: 'Numerical Methods and Fourier and Laplace Transformation',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 15,
    contactHours: 18,
  },
  {
    year: 3,
    semester: 2,
    title: 'Third Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-305',
        courseTitle: 'Electromagnetic Fields and Waves',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-309',
        courseTitle: 'Digital Signal Processing',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'EEE-310',
        courseTitle: 'Digital Signal Processing Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 4,
        courseCode: 'EEE-315',
        courseTitle: 'Electrical Measurements and Instrumentation',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-316',
        courseTitle: 'Electrical Measurements and Instrumentation Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'EEE-329',
        courseTitle: 'Electrical Machines-III',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 3,
    semester: 3,
    title: 'Third Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-307',
        courseTitle: 'Microprocessor and Interfacing',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-308',
        courseTitle: 'Microprocessor and Interfacing Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-318',
        courseTitle: 'Engineering Simulation Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 4,
        courseCode: 'EEE-345',
        courseTitle: 'Transmission and Distribution',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-347',
        courseTitle: 'Power Systems Engineering',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-449',
        courseTitle: 'Power Plant Engineering',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 4,
    semester: 1,
    title: 'Fourth Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-401',
        courseTitle: 'Control System',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-402',
        courseTitle: 'Control System Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-413',
        courseTitle: 'Electrical Engineering Materials',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-463',
        courseTitle: 'VLSI Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-464',
        courseTitle: 'VLSI Design Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'EEE-471',
        courseTitle: 'Wireless and Mobile Communication',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 4,
    semester: 2,
    title: 'Fourth Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-431',
        courseTitle: 'Power Electronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-432',
        courseTitle: 'Power Electronics Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-453',
        courseTitle: 'Power System Protection',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-455',
        courseTitle: 'Renewable Energy',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-459',
        courseTitle: 'Optoelectronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-473',
        courseTitle: 'Optical Fiber Communications',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 16,
    contactHours: 17,
  },
  {
    year: 4,
    semester: 3,
    title: 'Fourth Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-498',
        courseTitle: 'Project/Thesis',
        credit: 6,
        contactHours: 6,
      },
    ],
    total: 6,
    contactHours: 6,
  },
];
