import { ISemesterCourse } from '@/types';

/* -------------------------------------------------------------------------- */
/*                                 FIRST YEAR                                 */
/* -------------------------------------------------------------------------- */
export const firstYearFirstSemester: ISemesterCourse[] = [
  {
    code: 'PHY 117',
    course_name:
      'Structure of Matter, Electricity and Magnetism and Modern Physics',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3',
    prerequisite: '',
  },
  {
    code: 'CHM 115',
    course_name: 'Chemistry - I',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3',
    prerequisite: '',
  },
  {
    code: 'MTH 125',
    course_name: 'Differential Calculus, Solid Geometry and Vectors',
    contact_hours_theory: '4',
    contact_hours_sessional: '',
    credit: '4',
    prerequisite: '',
  },
  {
    code: 'ME 101',
    course_name: 'Introduction to Mechanical Engineering',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3',
    prerequisite: '',
  },
  {
    code: 'EEE 159',
    course_name: 'Fundamentals of Electrical Engineering',
    contact_hours_theory: '4',
    contact_hours_sessional: '',
    credit: '4',
    prerequisite: '',
  },
  {
    code: 'CHM 116',
    course_name: 'Inorganic Quantitative Analysis Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.5',
    prerequisite: '',
  },
  {
    code: 'EEE 160',
    course_name: 'Fundamentals of Electrical Engineering Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '.75',
    prerequisite: '',
  },
  {
    code: 'SHOP 160',
    course_name: 'Foundry and Welding Shops Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '.75',
    prerequisite: '',
  },
  {
    code: 'ME 160',
    course_name: 'Mechanical Engineering Drawing -I',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.5',
    prerequisite: '',
  },
];

export const firstYearSecondSemester: ISemesterCourse[] = [
  {
    code: 'PHY 119',
    course_name: 'Waves and Oscillation, Geometrical Optics and Wave Mechanics',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'CHM 117',
    course_name: 'Chemistry of Engineering Materials',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'MTH 127',
    course_name: 'Integral Calculus and Differential Equations',
    contact_hours_theory: '4',
    contact_hours_sessional: '',
    credit: '4.00',
    prerequisite: '',
  },
  {
    code: 'ME 171',
    course_name: 'Computer Programming Language',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'HUM101',
    course_name: 'English',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'PHY 120',
    course_name: 'Physics Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.50',
    prerequisite: '',
  },
  {
    code: 'ME 172',
    course_name: 'Computer Programming Language Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.50',
    prerequisite: '',
  },
  {
    code: 'SHOP 170',
    course_name: 'Machine Shop Practice',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
];

export const firstYearThirdSemester: ISemesterCourse[] = [
  {
    code: 'MTH-105',
    course_name:
      'Mathematics-III (Matrices, Vector Analysis and Fourier Series)',
    contact_hours_theory: '3',
    contact_hours_sessional: '0',
    credit: '3',
    prerequisite: '',
  },
  {
    code: 'CSE-131',
    course_name: 'Data Structures',
    contact_hours_theory: '3',
    contact_hours_sessional: '0',
    credit: '3',
    prerequisite: 'CSE-121',
  },
  {
    code: 'CSE-132',
    course_name: 'Data Structures Lab',
    contact_hours_theory: '0',
    contact_hours_sessional: '1.5',
    credit: '1.5',
    prerequisite: '',
  },
  {
    code: 'CSE-133',
    course_name: 'Numerical Methods',
    contact_hours_theory: '3',
    contact_hours_sessional: '0',
    credit: '3',
    prerequisite: 'MTH-103',
  },
  {
    code: 'EEE-103',
    course_name: 'Electronics Device and Circuits',
    contact_hours_theory: '3',
    contact_hours_sessional: '0',
    credit: '3',
    prerequisite: '',
  },
  {
    code: 'EEE-104',
    course_name: 'Electronics Device and Circuits Sessional',
    contact_hours_theory: '0',
    contact_hours_sessional: '1.5',
    credit: '1.5',
    prerequisite: '',
  },
];

/* -------------------------------------------------------------------------- */
/*                                 SECOND YEAR                                */
/* -------------------------------------------------------------------------- */
export const secondYearFirstSemester: ISemesterCourse[] = [
  {
    code: 'ME 247',
    course_name: 'Engineering Mechanics-I',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'EEE 259',
    course_name: 'Electrical and Electronics Technology',
    contact_hours_theory: '4',
    contact_hours_sessional: '',
    credit: '4.00',
    prerequisite: '',
  },
  {
    code: 'MTH 223',
    course_name:
      'Vector Calculus, Matrices, Laplace Transform and Series Solution',
    contact_hours_theory: '4',
    contact_hours_sessional: '',
    credit: '4.00',
    prerequisite: '',
  },
  {
    code: 'ME 203',
    course_name: 'Engineering Thermodynamics',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'HUM 201',
    course_name: 'Sociology',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'EEE 260',
    course_name: 'Electrical and Electronics Technology Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.50',
    prerequisite: '',
  },
  {
    code: 'ME 204',
    course_name: 'Engineering Thermodynamics Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
];

export const secondYearSecondSemester: ISemesterCourse[] = [
  {
    code: 'MME 291',
    course_name: 'Metallic Materials',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 261',
    course_name: 'Numerical Analysis',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 243',
    course_name: 'Mechanics of Solids',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'MTH 225',
    course_name:
      'Complex Variables, Harmonic Analysis and Partial Differential Equations',
    contact_hours_theory: '4',
    contact_hours_sessional: '',
    credit: '4.00',
    prerequisite: '',
  },
  {
    code: 'ME 249',
    course_name: 'Engineering Mechanics-II',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'MME 292',
    course_name: 'Metallic Materials Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.50',
    prerequisite: '',
  },
  {
    code: 'ME 262',
    course_name: 'Numerical Analysis Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'ME 244',
    course_name: 'Mechanics of Solids Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'ME 260',
    course_name: 'Mechanical Engineering Drawing -II',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.50',
    prerequisite: '',
  },
];

export const secondYearThirdSemester: ISemesterCourse[] = [
  {
    code: 'CSE-231',
    course_name: 'Operating Systems',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3',
    prerequisite: 'CSE-221',
  },
  {
    code: 'CSE-232',
    course_name: 'Operating Systems Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '1.5',
    prerequisite: '',
  },
  {
    code: 'CSE-233',
    course_name: 'System Analysis and Design',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3',
    prerequisite: 'CSE-223',
  },
  {
    code: 'CSE-234',
    course_name: 'System Analysis and Design Lab',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '1.5',
    prerequisite: '',
  },
  {
    code: 'CSE-235',
    course_name: 'Computer Architecture',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3',
    prerequisite: 'CSE-131, CSE-132',
  },
  {
    code: 'CSE-236',
    course_name: 'Assembly Language Programming Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1',
    credit: '1',
    prerequisite: 'N/A',
  },
];

/* -------------------------------------------------------------------------- */
/*                                 THIRD YEAR                                 */
/* -------------------------------------------------------------------------- */
export const thirdYearFirstSemester: ISemesterCourse[] = [
  {
    code: 'IPE 331',
    course_name: 'Production Processes',
    contact_hours_theory: '4',
    contact_hours_sessional: '',
    credit: '4.00',
    prerequisite: '',
  },
  {
    code: 'ME 321',
    course_name: 'Fluid Mechanics - I',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 349',
    course_name: 'Mechanics of Machinery',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 305',
    course_name: 'Heat Transfer',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 361',
    course_name: 'Instrumentation and Measurement',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'IPE 332',
    course_name: 'Production Process Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'ME 350',
    course_name: 'Mechanics of Machinery Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.5',
    prerequisite: '',
  },
  {
    code: 'ME 306',
    course_name: 'Heat Transfer Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'ME 366',
    course_name: 'Electro-Mechanical System Design and Practice',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.50',
    prerequisite: '',
  },
];

export const thirdYearSecondSemester: ISemesterCourse[] = [
  {
    code: 'HUM 303',
    course_name: 'Principles of Accounting',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 323',
    course_name: 'Fluid Mechanics -II',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 351',
    course_name: 'Machine Design',
    contact_hours_theory: '4',
    contact_hours_sessional: '',
    credit: '4.00',
    prerequisite: '',
  },
  {
    code: 'IPE 381',
    course_name: 'Measurement and Quality Control',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 307',
    course_name: 'Heat Transfer Equipment Design',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 326',
    course_name: 'Fluid Mechanics Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'ME 352',
    course_name: 'Machine Design Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.50',
    prerequisite: '',
  },
  {
    code: 'IPE 382',
    course_name: 'Measurement and Quality Control Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'ME 310',
    course_name: 'Thermo Fluid System Design',
    contact_hours_theory: '',
    contact_hours_sessional: '3',
    credit: '1.50',
    prerequisite: '',
  },
  {
    code: 'ME 370',
    course_name: 'Industrial Training',
    contact_hours_theory: '',
    contact_hours_sessional: '4',
    credit: '4',
    prerequisite: '',
  },
];

export const thirdYearThirdSemester: ISemesterCourse[] = [
  {
    code: 'CSE-331',
    course_name: 'Computer Network',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3',
    prerequisite: 'CSE-417',
  },
  {
    code: 'CSE-332',
    course_name: 'Computer Networks Lab',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '1.5',
    prerequisite: 'N/A',
  },
  {
    code: 'CSE-333',
    course_name: 'Pattern Recognition',
    contact_hours_theory: '6',
    contact_hours_sessional: '3',
    credit: '9',
    prerequisite: 'CSE-311',
  },
  {
    code: 'CSE-334',
    course_name: 'Pattern Recognition Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: 'Base on CSE-333',
  },
  {
    code: 'CSE-335',
    course_name: 'Computer Graphics',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: 'MTH-221, 207',
  },
  {
    code: 'CSE-336',
    course_name: 'Computer Graphics Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: '',
  },
  {
    code: 'CSE-337',
    course_name: 'Simulation & Modeling',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: '',
  },
  {
    code: 'CSE-338',
    course_name: 'Simulation & Modeling Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: '',
  },
  {
    code: 'CSE-339',
    course_name: 'Multimedia Systems Design',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: 'CSE-331',
  },
  {
    code: 'CSE-340',
    course_name: 'Multimedia Systems Design Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: '',
  },
  {
    code: 'CSE-341',
    course_name: 'VLSI Design',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: 'CSE-131',
  },
  {
    code: 'CSE-342',
    course_name: 'VLSI Design Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: '',
  },
  {
    code: 'CSE-343',
    course_name: 'Advanced Object Oriented Programming',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: 'CSE-211',
  },
  {
    code: 'CSE-344',
    course_name: 'Advanced Object Oriented Programming Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '',
    credit: '',
    prerequisite: '',
  },
];

/* -------------------------------------------------------------------------- */
/*                                 FOURTH YEAR                                */
/* -------------------------------------------------------------------------- */
export const fourthYearFirstSemester: ISemesterCourse[] = [
  {
    code: 'ME 421',
    course_name: 'Fluid Machinery',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'IPE 431',
    course_name: 'Machine Tools',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 417',
    course_name: 'Internal Combustion Engines',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'Optional-a²',
    course_name: 'Selected from prescribed optional subjects',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'Optional-b²',
    course_name: 'Selected from prescribed optional subjects',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 422',
    course_name: 'Fluid Machinery Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'IPE 432',
    course_name: 'Machine Tools Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'ME 418',
    course_name: 'Heat Engines Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'ME 400',
    course_name: 'Project and Thesis',
    contact_hours_theory: '',
    contact_hours_sessional: '6',
    credit: '3.00',
    prerequisite: '',
  },
];

export const fourthYearSecondSemester: ISemesterCourse[] = [
  {
    code: 'ME 421',
    course_name: 'Fluid Machinery',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'IPE 431',
    course_name: 'Machine Tools',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 417',
    course_name: 'Internal Combustion Engines',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'Optional-a²',
    course_name: 'Selected from prescribed optional subjects',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'Optional-b²',
    course_name: 'Selected from prescribed optional subjects',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3.00',
    prerequisite: '',
  },
  {
    code: 'ME 422',
    course_name: 'Fluid Machinery Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'IPE 432',
    course_name: 'Machine Tools Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'ME 418',
    course_name: 'Heat Engines Sessional',
    contact_hours_theory: '',
    contact_hours_sessional: '1.5',
    credit: '0.75',
    prerequisite: '',
  },
  {
    code: 'ME 400',
    course_name: 'Project and Thesis',
    contact_hours_theory: '',
    contact_hours_sessional: '6',
    credit: '3.00',
    prerequisite: '',
  },
];

export const fourthYearThirdSemester: ISemesterCourse[] = [
  {
    code: 'CSE-430',
    course_name: 'Project & Thesis',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3',
    prerequisite: '',
  },
  {
    code: 'CSE-440',
    course_name: 'Industrial Training',
    contact_hours_theory: '3',
    contact_hours_sessional: '',
    credit: '3',
    prerequisite: '',
  },
];
