import { ICareer } from '@/types';

export const jobsOpening: ICareer[] = [
  {
    title: 'Assistant Professor of Computer Science',
    faculty: 'Faculty of Engineering and Technology',
    category: 'Academic',
    location: 'Boston, MA',
    deadline: '2025-02-15',
    pdf: '/pdf/test.pdf',
  },
  {
    title: 'Lecturer in Mathematics',
    faculty: 'Faculty of Science',
    category: 'Academic',
    location: 'San Francisco, CA',
    deadline: '2025-03-01',
    pdf: '/pdf/test.pdf',
  },
  {
    title: 'Research Associate in Environmental Science',
    faculty: 'Faculty of Science',
    category: 'Research',
    location: 'Seattle, WA',
    deadline: '2025-02-28',
    pdf: '/pdf/test.pdf',
  },
  {
    title: 'Administrative Officer',
    faculty: 'Faculty of Arts and Humanities',
    category: 'Administrative',
    location: 'New York, NY',
    deadline: '2025-02-10',
    pdf: '/pdf/test.pdf',
  },
  {
    title: 'Director of Student Affairs',
    faculty: 'Faculty of Social Sciences',
    category: 'Management',
    location: 'Chicago, IL',
    deadline: '2025-03-05',
    pdf: '/pdf/test.pdf',
  },
  {
    title: 'Postdoctoral Fellow in Physics',
    faculty: 'Faculty of Science',
    category: 'Research',
    location: 'Cambridge, UK',
    deadline: '2025-02-20',
    pdf: '/pdf/test.pdf',
  },
  {
    title: 'Senior Lecturer in Law',
    faculty: 'Faculty of Law',
    category: 'Academic',
    location: 'Toronto, Canada',
    deadline: '2025-03-12',
    pdf: '/pdf/test.pdf',
  },
  {
    title: 'Head of Marketing and Communications',
    faculty: 'Faculty of Business and Economics',
    category: 'Management',
    location: 'Los Angeles, CA',
    deadline: '2025-02-25',
    pdf: '/pdf/test.pdf',
  },
  {
    title: 'Library Technician',
    faculty: 'Faculty of Education',
    category: 'Support Staff',
    location: 'Vancouver, Canada',
    deadline: '2025-03-18',
    pdf: '/pdf/test.pdf',
  },
  {
    title: 'IT Systems Administrator',
    faculty: 'Faculty of Engineering and Technology',
    category: 'Technical',
    location: 'Austin, TX',
    deadline: '2025-03-08',
    pdf: '/pdf/test.pdf',
  },
];
