import { ISemesterCourse } from '@/types';

/* -------------------------------------------------------------------------- */
/*                                 FIRST YEAR                                 */
/* -------------------------------------------------------------------------- */
export const firstYearFirstSemester: ISemesterCourse[] = [
	{
		code: 'PHY-101',
		course_name: 'Physics',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'PHY-102',
		course_name: 'Physics Sessional',
		contact_hours_theory: '–',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: '',
	},
	{
		code: 'CHM-101',
		course_name: 'Chemistry',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'ENG-101',
		course_name: 'Foundation English',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'MTH-101',
		course_name: 'Mathematics-I (Differential and Integral Calculus)',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'CSE-100',
		course_name: 'Introduction to Computer Systems',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'N/A',
	},
];

export const firstYearSecondSemester: ISemesterCourse[] = [
	{
		code: 'MTH-103',
		course_name: 'Mathematics-II (Ordinary and Partial Differential Equations)',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'CSE-121',
		course_name: 'Structured Programming Language',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'N/A',
	},
	{
		code: 'CSE-122',
		course_name: 'Structured Programming Language Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: 'N/A',
	},
	{
		code: 'CSE-123',
		course_name: 'Discrete Mathematics',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'N/A',
	},
	{
		code: 'EEE-101',
		course_name: 'Introduction to Electrical Engineering',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'N/A',
	},
	{
		code: 'EEE-102',
		course_name: 'Introduction to Electrical Engineering Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: 'N/A',
	},
];

export const firstYearThirdSemester: ISemesterCourse[] = [
	{
		code: 'MTH-105',
		course_name: 'Mathematics-III (Matrices, Vector Analysis and Fourier Series)',
		contact_hours_theory: '3',
		contact_hours_sessional: '0',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'CSE-131',
		course_name: 'Data Structures',
		contact_hours_theory: '3',
		contact_hours_sessional: '0',
		credit: '3',
		prerequisite: 'CSE-121',
	},
	{
		code: 'CSE-132',
		course_name: 'Data Structures Lab',
		contact_hours_theory: '0',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: '',
	},
	{
		code: 'CSE-133',
		course_name: 'Numerical Methods',
		contact_hours_theory: '3',
		contact_hours_sessional: '0',
		credit: '3',
		prerequisite: 'MTH-103',
	},
	{
		code: 'EEE-103',
		course_name: 'Electronics Device and Circuits',
		contact_hours_theory: '3',
		contact_hours_sessional: '0',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'EEE-104',
		course_name: 'Electronics Device and Circuits Sessional',
		contact_hours_theory: '0',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: '',
	},
];

/* -------------------------------------------------------------------------- */
/*                                 SECOND YEAR                                */
/* -------------------------------------------------------------------------- */
export const secondYearFirstSemester: ISemesterCourse[] = [
	{
		code: 'MTH-207',
		course_name: 'Mathematics-IV (Complex Variable and Laplace Transform)',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'CSE-211',
		course_name: 'Object Oriented Programming Language',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE 121',
	},
	{
		code: 'CSE-212',
		course_name: 'Object Oriented Programming Language Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: 'CSE-122',
	},
	{
		code: 'EEE-201',
		course_name: 'Electrical Drives and Instrumentation',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'EEE-202',
		course_name: 'Electrical Drives and Instrumentation Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: '',
	},
	{
		code: 'CSE-213',
		course_name: 'Digital Logic Design',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'N/A',
	},
	{
		code: 'CSE-214',
		course_name: 'Digital Logic Design Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: 'N/A',
	},
];

export const secondYearSecondSemester: ISemesterCourse[] = [
	{
		code: 'ACT-201',
		course_name: 'Financial & Managerial Accounting',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'MTH-221',
		course_name: 'Mathematics-V (Statistics and Coordinate Geometry)',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'CSE-221',
		course_name: 'Algorithms',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-121, CSE-123',
	},
	{
		code: 'CSE-222',
		course_name: 'Algorithms Lab',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: '',
	},
	{
		code: 'CSE-223',
		course_name: 'Database Management Systems',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'CSE-224',
		course_name: 'Database Management Systems Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: '',
	},
];

export const secondYearThirdSemester: ISemesterCourse[] = [
	{
		code: 'CSE-231',
		course_name: 'Operating Systems',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-221',
	},
	{
		code: 'CSE-232',
		course_name: 'Operating Systems Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: '',
	},
	{
		code: 'CSE-233',
		course_name: 'System Analysis and Design',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-223',
	},
	{
		code: 'CSE-234',
		course_name: 'System Analysis and Design Lab',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: '',
	},
	{
		code: 'CSE-235',
		course_name: 'Computer Architecture',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-131, CSE-132',
	},
	{
		code: 'CSE-236',
		course_name: 'Assembly Language Programming Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1',
		credit: '1',
		prerequisite: 'N/A',
	},
];

/* -------------------------------------------------------------------------- */
/*                                 THIRD YEAR                                 */
/* -------------------------------------------------------------------------- */
export const thirdYearFirstSemester: ISemesterCourse[] = [
	{
		code: 'CSE-315',
		course_name: 'Theory of Computing',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-221, 222,123',
	},
	{
		code: 'CSE-311',
		course_name: 'Artificial Intelligence',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-221',
	},
	{
		code: 'CSE-312',
		course_name: 'Artificial Intelligence Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: 'CSE-222',
	},
	{
		code: 'CSE-317',
		course_name: 'Data Communication',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'MTH-105',
	},
	{
		code: 'CSE-313',
		course_name: 'Microprocessor and Microcontroller',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-325',
	},
	{
		code: 'CSE-314',
		course_name: 'Microprocessor and Microcontroller Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: 'CSE-326',
	},
];

export const thirdYearSecondSemester: ISemesterCourse[] = [
	{
		code: 'CSE-323',
		course_name: 'Compiler',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-316',
	},
	{
		code: 'CSE-324',
		course_name: 'Compiler Lab',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: '',
	},
	{
		code: 'CSE-321',
		course_name: 'Software Engineering',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-233',
	},
	{
		code: 'CSE-322',
		course_name: 'Software Engineering Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: 'CSE-234',
	},
	{
		code: 'CSE-325',
		course_name: 'Digital System Design',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-236',
	},
	{
		code: 'CSE-326',
		course_name: 'Digital System Design Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: '',
	},
];

export const thirdYearThirdSemester: ISemesterCourse[] = [
	{
		code: 'CSE-331',
		course_name: 'Computer Network',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: 'CSE-417',
	},
	{
		code: 'CSE-332',
		course_name: 'Computer Networks Lab',
		contact_hours_theory: '',
		contact_hours_sessional: '1.5',
		credit: '1.5',
		prerequisite: 'N/A',
	},
	{
		code: 'CSE-333',
		course_name: 'Pattern Recognition',
		contact_hours_theory: '6',
		contact_hours_sessional: '3',
		credit: '9',
		prerequisite: 'CSE-311',
	},
	{
		code: 'CSE-334',
		course_name: 'Pattern Recognition Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'Base on CSE-333',
	},
	{
		code: 'CSE-335',
		course_name: 'Computer Graphics',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'MTH-221, 207',
	},
	{
		code: 'CSE-336',
		course_name: 'Computer Graphics Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: '',
	},
	{
		code: 'CSE-337',
		course_name: 'Simulation & Modeling',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: '',
	},
	{
		code: 'CSE-338',
		course_name: 'Simulation & Modeling Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: '',
	},
	{
		code: 'CSE-339',
		course_name: 'Multimedia Systems Design',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-331',
	},
	{
		code: 'CSE-340',
		course_name: 'Multimedia Systems Design Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: '',
	},
	{
		code: 'CSE-341',
		course_name: 'VLSI Design',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-131',
	},
	{
		code: 'CSE-342',
		course_name: 'VLSI Design Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: '',
	},
	{
		code: 'CSE-343',
		course_name: 'Advanced Object Oriented Programming',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-211',
	},
	{
		code: 'CSE-344',
		course_name: 'Advanced Object Oriented Programming Sessional',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: '',
	},
];

/* -------------------------------------------------------------------------- */
/*                                 FOURTH YEAR                                */
/* -------------------------------------------------------------------------- */
export const fourthYearFirstSemester: ISemesterCourse[] = [
	{
		code: 'ECO-201',
		course_name: 'Engineering Economics',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'CSE-417',
		course_name: 'Project Management',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'CSE-400',
		course_name: 'Project & Thesis',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
];

export const fourthYearSecondSemester: ISemesterCourse[] = [
	{
		code: 'MGT-201',
		course_name: 'Industrial and Operational Management',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'CSE-421',
		course_name: 'Optical Fiber Communication',
		contact_hours_theory: '9',
		contact_hours_sessional: '',
		credit: '9',
		prerequisite: 'CSE-331',
	},
	{
		code: 'CSE-423',
		course_name: 'Mobile Cellular Communication',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-331',
	},
	{
		code: 'CSE-425',
		course_name: 'Wireless Communication',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-331',
	},
	{
		code: 'CSE-427',
		course_name: 'E-Commerce',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-331',
	},
	{
		code: 'CSE-429',
		course_name: 'Web Programming',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-223',
	},
	{
		code: 'CSE-441',
		course_name: 'Advanced DBMS',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-321',
	},
	{
		code: 'CSE-443',
		course_name: 'Advanced Network Services and Management',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-331',
	},
	{
		code: 'CSE-445',
		course_name: 'Mobile Computing',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-331',
	},
	{
		code: 'CSE-447',
		course_name: 'Network Security',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-331',
	},
	{
		code: 'CSE-449',
		course_name: 'Embedded Systems',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-331',
	},
	{
		code: 'CSE-451',
		course_name: 'Mobile Application Development',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-313',
	},
	{
		code: 'CSE-453',
		course_name: 'Digital Image Processing',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'CSE-211',
	},
	{
		code: 'CSE-455',
		course_name: 'Game Design & Development',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'MTH-105, CSE-121',
	},
	{
		code: 'CSE-457',
		course_name: 'Cloud Computing',
		contact_hours_theory: '',
		contact_hours_sessional: '',
		credit: '',
		prerequisite: 'N/A',
	},
];

export const fourthYearThirdSemester: ISemesterCourse[] = [
	{
		code: 'CSE-430',
		course_name: 'Project & Thesis',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
	{
		code: 'CSE-440',
		course_name: 'Industrial Training',
		contact_hours_theory: '3',
		contact_hours_sessional: '',
		credit: '3',
		prerequisite: '',
	},
];
