import type { Metadata } from 'next';

import { Inter, Poppins } from 'next/font/google';

import './globals.css';
import { cn } from '@/lib/utils';
import Layout from '@/components/layout';
import Providers from '@/components/providers';
import { Toaster } from 'sonner';

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});
const fontPoppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(
          'font-sans antialiased',
          fontSans.variable,
          fontPoppins.variable
        )}
      >
        <Providers>
          <Layout>{children}</Layout>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
