export type SiteConfig = typeof siteConfig;

export const siteUrl = 'https://eub.edu.bd/';

export const siteConfig = {
  name: 'European University of Bangladesh',
  description:
    'The European University of Bangladesh has started its journey towards achieving excellence in higher education in this country. In its consideration, the fount of progress in Europe has been higher education centering around science and technology. In search of excellence, the European University of Bangladesh will, go at length, to emulate the ways traversed by universities and institutions of higher education and learning in Europe.For Math Department students: Calculate your yearly and overall CGPA in seconds. Print official-looking academic transcripts directly from our easy-to-use online tool.',
  url: siteUrl,
  ogImage: `${siteUrl}/opengraph-image.jpg`,
  keywords: [
    'European University of Bangladesh',
    'EUB',
    'EUB Bangladesh',
    'European University Dhaka',
    'www.eub.edu.bd',
    'ইউরোপিয়ান ইউনিভার্সিটি অব বাংলাদেশ',
    'EUB programs',
    'European University courses',
    'Undergraduate programs at EUB',
    'Postgraduate programs at EUB',
    'EUB admission',
    'Civil Engineering at EUB',
    'Computer Science & Engineering (CSE) in Bangladesh',
    'Electrical & Electronic Engineering (EEE) university',
    'Textile Engineering private university',
    'Industrial & Production Engineering (IPE)',
    'Mechanical Engineering degree',
    'BBA admission in Dhaka',
    'MBA in Bangladesh',
    'Executive MBA (EMBA) programs',
    'Tourism & Hospitality Management degree',
    'LLB degree in Bangladesh',
    'BA in English private university',
    'Economics (BSS/MSS) in Dhaka',
    'LLM program Bangladesh',
    'Affordable private university in Bangladesh',
    'Low tuition fee university in Dhaka',
    'European standard education in Bangladesh',
    'UGC approved private university',
    'Student-centered learning',
    'Globally competitive graduates',
    'Career development opportunities',
    'EUB scholarships and waivers',
    'University with large permanent campus',
    'Hands-on experience for students',
    'Student involvement in university projects',
    'Private university in Dhaka',
    'Best private university in Gabtoli',
    'University near Gabtoli Bus Terminal',
    'Top universities in Mirpur',
    'Higher education in Dhaka City',
    'Private university admission 2025',
    'How to apply to EUB',
    'EUB tuition fees and costs',
    'European University of Bangladesh ranking',
    'EUB contact number',
    'EUB student portal',
    'Private university for middle-class students',
    'Best private university for engineering in Bangladesh',
    'Working student university programs Dhaka',
    'Top private universities in Bangladesh',
    'EUB vs Competitor University',
    'Best private universities for CSE in Dhaka',
    'Affordable BBA programs in Bangladesh',
    'College and university rankings',
    'QS World University Rankings',
    'Times Higher Education World University Rankings',
    'Tuition Fee Cost',
    'Scholarship',
    'Best Private University in Bangladesh',
    'Top Rated University',
    'Top Ranked University in Bangladesh',
    'UGC Approved University',
    'CSE',
    'Computer Science and Engineering',
    'BBA',
    'EEE',
    'LLB',
    'LLM',
    'MBA',
    'Executive MBA',
    'English',
  ],
};
