import type {
  Course,
  CoursePrefix,
  CurriculumSummary,
  ElectiveCourse,
  PerformanceEvaluation,
  ProgramDetails,
  Semester,
} from '@/app/programs/_config/curriculum';

export const eeeSemesterInfo = {
  spring: 'January-April',
  summer: 'May-August',
  fall: 'September-December',
};

export const eeeRegularProgramDetails: ProgramDetails = {
  degreeName:
    'Bachelor of Science in Electrical and Electronic Engineering (B.Sc. in EEE)',
  duration: {
    years: 4,
    semesters: 12,
  },
  creditHours: 160,
  courseLoad: '16 Weeks/Semester',
  courseLoadDetails:
    'Classes and continuous assessments: 12 weeks, Mid Term and Semester Final Examinations: 4 weeks',
  minimumGPA: 2.2,
  backgroundStudents: 'For HSC Passed Students',
};

export const eeeEveningProgramDetails: ProgramDetails = {
  degreeName:
    'Bachelor of Science in Electrical and Electronic Engineering (B.Sc. in EEE)',
  duration: {
    years: '3 years, 4 months',
    semesters: 10,
  },
  creditHours: '160 (142 + 18 waived)',
  courseLoad: '16 Weeks/Semester',
  courseLoadDetails:
    'Classes and continuous assessments: 12 weeks, Mid Term and Semester Final Examinations: 4 weeks',
  minimumGPA: 2.2,
  backgroundStudents: 'For Diploma in Engineering Passed Students',
  waiverInfo:
    'The first two (02) semesters, totaling 18.00 credits, are waived for Evening batch students who have completed a diploma in engineering degree.',
};

export const eeePerformanceEvaluation: PerformanceEvaluation[] = [
  {
    category: '(a) Theory Courses:',
    criteria: [
      { item: 'Class Participation (Attendance)', percentage: '20%' },
      {
        item: 'Continuous Assessment (Class Tests, Assignments, Presentations etc.)',
        percentage: '20%',
      },
      { item: 'Mid Term Examination', percentage: '30%' },
      { item: 'Semester Final Examination', percentage: '30%' },
    ],
  },
  {
    category: '(b) Courses on Laboratory/Sessional/Field Work:',
    criteria: [
      { item: 'Class Participation (Attendance)', percentage: '20%' },
      { item: 'Quiz', percentage: '20%' },
      { item: 'Viva Voce', percentage: '20%' },
      { item: 'Performance/Reports', percentage: '40%' },
    ],
  },
  {
    category: '(c) Project/Thesis:',
    criteria: [
      { item: 'Book', percentage: '10%' },
      { item: 'Presentation and Viva-Voce', percentage: '20%' },
      { item: 'Committee', percentage: '20%' },
      { item: 'Supervisor', percentage: '50%' },
    ],
  },
];

export const eeeCoreCoursesData: Course[] = [
  {
    sl: 1,
    code: 'EEE-100',
    title: 'Electrical Drawing and Drafting Lab',
    credits: 1,
  },
  { sl: 2, code: 'EEE-101', title: 'Electrical Circuits-I', credits: 3 },
  { sl: 3, code: 'EEE-102', title: 'Electrical Circuits-I Lab', credits: 1 },
  { sl: 4, code: 'EEE-103', title: 'Electrical Circuits-II', credits: 3 },
  { sl: 5, code: 'EEE-104', title: 'Electrical Circuits-II Lab', credits: 1 },
  { sl: 6, code: 'EEE-201', title: 'Electronics-I', credits: 3 },
  { sl: 7, code: 'EEE-202', title: 'Electronics-I Lab', credits: 1 },
  { sl: 8, code: 'EEE-203', title: 'Electrical Machines-I', credits: 3 },
  { sl: 9, code: 'EEE-204', title: 'Electrical Machines-I Lab', credits: 1 },
  { sl: 10, code: 'EEE-205', title: 'Electronics-II', credits: 3 },
  { sl: 11, code: 'EEE-206', title: 'Electronics-II Lab', credits: 1 },
  { sl: 12, code: 'EEE-207', title: 'Digital Logic Design', credits: 3 },
  { sl: 13, code: 'EEE-208', title: 'Digital Logic Design Lab', credits: 1 },
  { sl: 14, code: 'EEE-209', title: 'Electrical Machines-II', credits: 3 },
  {
    sl: 15,
    code: 'EEE-210',
    title: 'Electrical Machines-II Lab',
    credits: 1,
  },
  { sl: 16, code: 'EEE-211', title: 'Semiconductor Device', credits: 3 },
  { sl: 17, code: 'EEE-301', title: 'Digital Electronics', credits: 3 },
  { sl: 18, code: 'EEE-302', title: 'Digital Electronics Lab', credits: 1 },
  { sl: 19, code: 'EEE-303', title: 'Signals and Systems', credits: 3 },
  { sl: 20, code: 'EEE-304', title: 'Signals and Systems Lab', credits: 1 },
  {
    sl: 21,
    code: 'EEE-305',
    title: 'Electromagnetic Fields and Waves',
    credits: 3,
  },
  {
    sl: 22,
    code: 'EEE-307',
    title: 'Microprocessor and Interfacing',
    credits: 3,
  },
  {
    sl: 23,
    code: 'EEE-308',
    title: 'Microprocessor and Interfacing Lab',
    credits: 1,
  },
  { sl: 24, code: 'EEE-309', title: 'Digital Signal Processing', credits: 3 },
  {
    sl: 25,
    code: 'EEE-310',
    title: 'Digital Signal Processing Lab',
    credits: 1,
  },
  { sl: 26, code: 'EEE-311', title: 'Communication Engineering', credits: 3 },
  {
    sl: 27,
    code: 'EEE-312',
    title: 'Communication Engineering Lab',
    credits: 1,
  },
  {
    sl: 28,
    code: 'EEE-315',
    title: 'Electrical Measurements and Instrumentation',
    credits: 3,
  },
  {
    sl: 29,
    code: 'EEE-316',
    title: 'Electrical Measurements and Instrumentation Lab',
    credits: 1,
  },
  {
    sl: 30,
    code: 'EEE-318',
    title: 'Engineering Simulation Lab',
    credits: 1,
  },
  { sl: 31, code: 'EEE-329', title: 'Electrical Machines-III', credits: 3 },
  {
    sl: 32,
    code: 'EEE-345',
    title: 'Transmission and Distribution',
    credits: 3,
  },
  { sl: 33, code: 'EEE-347', title: 'Power Systems Engineering', credits: 3 },
  { sl: 34, code: 'EEE-401', title: 'Control System', credits: 3 },
  { sl: 35, code: 'EEE-402', title: 'Control System Lab', credits: 1 },
  {
    sl: 36,
    code: 'EEE-413',
    title: 'Electrical Engineering Materials',
    credits: 3,
  },
  { sl: 37, code: 'EEE-431', title: 'Power Electronics', credits: 3 },
  { sl: 38, code: 'EEE-432', title: 'Power Electronics Lab', credits: 1 },
  { sl: 39, code: 'EEE-449', title: 'Power Plant Engineering', credits: 3 },
  { sl: 40, code: 'EEE-463', title: 'VLSI Design', credits: 3 },
  { sl: 41, code: 'EEE-464', title: 'VLSI Design Lab', credits: 1 },
];

export const eeeGeneralEducationCourses: Course[] = [
  {
    sl: 1,
    code: 'GED-101',
    title: 'Bangladesh Studies (History of Independence of Bangladesh)',
    credits: 3,
  },
  { sl: 2, code: 'ENG-101', title: 'Oral and Written English', credits: 3 },
  {
    sl: 3,
    code: 'BBA-103',
    title: 'Financial & Managerial Accounting',
    credits: 3,
  },
  { sl: 4, code: 'GED-103', title: 'Introduction to Sociology', credits: 3 },
  { sl: 5, code: 'BBA-201', title: 'Business Communication', credits: 3 },
  {
    sl: 6,
    code: 'BBA-207',
    title: 'Industrial and Operational Management',
    credits: 3,
  },
  { sl: 7, code: 'GED-301', title: 'Professional Ethics', credits: 3 },
  { sl: 8, code: 'BBA-313', title: 'Industrial Economics', credits: 3 },
];

export const eeeBasicScienceCourses: Course[] = [
  { sl: 1, code: 'PHY-101', title: 'Physics-I', credits: 3 },
  { sl: 2, code: 'PHY-102', title: 'Physics-I Lab', credits: 1 },
  { sl: 3, code: 'PHY-103', title: 'Physics-II', credits: 3 },
  { sl: 4, code: 'PHY-104', title: 'Physics-II Lab', credits: 1 },
  { sl: 5, code: 'CHM-101', title: 'Chemistry', credits: 3 },
  { sl: 6, code: 'CHM-102', title: 'Chemistry Lab', credits: 1 },
  {
    sl: 7,
    code: 'MTH-101',
    title: 'Differential and Integral Calculus',
    credits: 3,
  },
  { sl: 8, code: 'MTH-103', title: 'Differential Equations', credits: 3 },
  {
    sl: 9,
    code: 'MTH-201',
    title: 'Linear Algebra and Complex Variable',
    credits: 3,
  },
  {
    sl: 10,
    code: 'MTH-203',
    title: 'Probability and Statistics',
    credits: 3,
  },
  {
    sl: 11,
    code: 'MTH-205',
    title: 'Co-ordinate Geometry and Vector Analysis',
    credits: 3,
  },
  {
    sl: 12,
    code: 'MTH-301',
    title: 'Numerical Methods and Fourier and Laplace Transformation',
    credits: 3,
  },
];

export const eeeInterDisciplinaryCourses: Course[] = [
  { sl: 1, code: 'CSE-203', title: 'Programming Language', credits: 3 },
  { sl: 2, code: 'CSE-204', title: 'Programming Language Lab', credits: 1 },
  {
    sl: 3,
    code: 'ME-201',
    title: 'Mechanical Engineering Fundamentals',
    credits: 3,
  },
  { sl: 4, code: 'EEE-285', title: 'Biomedical Electronics', credits: 3 },
];

export const eeeElectiveCourses: ElectiveCourse[] = [
  {
    sl: 1,
    codes: ['EEE-333', 'EEE-335', 'EEE-339'],
    titles: [
      'Operation and Control of Power System',
      'Digital Integrated Circuit Design',
      'RF and Microwave Engineering',
    ],
    credits: 3,
  },
  {
    sl: 2,
    codes: ['EEE-451', 'EEE-337', 'EEE-467'],
    titles: [
      'High Voltage Engineering',
      'Digital Communication Electronics',
      'Telecommunications Networks & Switching',
    ],
    credits: 3,
  },
  {
    sl: 3,
    codes: ['EEE-453', 'EEE-457', 'EEE-469'],
    titles: [
      'Power System Protection',
      'Semiconductor Processing and Fabrication',
      'Digital Communication',
    ],
    credits: 3,
  },
  {
    sl: 4,
    codes: ['EEE-455', 'EEE-459', 'EEE-471'],
    titles: [
      'Renewable Energy',
      'Optoelectronics',
      'Wireless and Mobile Communication',
    ],
    credits: 3,
  },
  {
    sl: 5,
    codes: ['EEE-461', 'EEE-473', 'EEE-475'],
    titles: [
      'Analog Integrated Circuits',
      'Optical Fiber Communications',
      'Satellite Communication',
    ],
    credits: 3,
  },
];

export const eeeProjectCourses: Course[] = [
  { sl: 1, code: 'EEE-498', title: 'Project/Thesis', credits: 6 },
];

export const eeeCoursePrefixes: CoursePrefix[] = [
  { symbol: 'BBA', name: 'Business Administration' },
  { symbol: 'GED', name: 'General Education' },
  { symbol: 'CHM', name: 'Chemistry' },
  { symbol: 'ME', name: 'Mechanical Engineering' },
  { symbol: 'CSE', name: 'Computer Science and Engineering' },
  { symbol: 'MTH', name: 'Mathematics' },
  { symbol: 'EEE', name: 'Electrical and Electronic Engineering' },
  { symbol: 'PHY', name: 'Physics' },
  { symbol: 'ENG', name: 'English' },
];

export const eeeCurriculumSummary: CurriculumSummary[] = [
  {
    category: 'Core Courses',
    credits: 87,
  },
  {
    category: 'Elective Courses',
    credits: 15,
  },
  {
    category: 'Basic Science and Mathematics Courses',
    credits: 30,
  },
  {
    category: 'General Education Courses: English & Others',
    credits: 15,
  },
  {
    category: 'Inter-Disciplinary Engineering Courses',
    credits: 7,
  },
  {
    category: 'Project/Thesis',
    credits: 6,
  },
];

// HSC Background Students - Regular Program
export const eeeRegularSemesterData: Semester[] = [
  {
    year: 1,
    semester: 1,
    title: 'First Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-101',
        courseTitle: 'Electrical Circuits-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-102',
        courseTitle: 'Electrical Circuits-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'MTH-101',
        courseTitle: 'Differential and Integral Calculus',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CHM-101',
        courseTitle: 'Chemistry',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'CHM-102',
        courseTitle: 'Chemistry Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'PHY-101',
        courseTitle: 'Physics-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 7,
        courseCode: 'PHY-102',
        courseTitle: 'Physics-I Lab',
        credit: 1,
        contactHours: 2,
      },
    ],
    total: 15,
    contactHours: 18,
  },
  {
    year: 1,
    semester: 2,
    title: 'First Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-103',
        courseTitle: 'Electrical Circuits-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-104',
        courseTitle: 'Electrical Circuits-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'MTH-103',
        courseTitle: 'Differential Equations',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'PHY-103',
        courseTitle: 'Physics-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'PHY-104',
        courseTitle: 'Physics-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'ENG-101',
        courseTitle: 'Oral and Written English',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 1,
    semester: 3,
    title: 'First Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-201',
        courseTitle: 'Electronics-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-202',
        courseTitle: 'Electronics-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-100',
        courseTitle: 'Electrical Drawing and Drafting Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 4,
        courseCode: 'GED-101',
        courseTitle:
          'Bangladesh Studies (History of Independence of Bangladesh)',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'BBA-103',
        courseTitle: 'Financial and Managerial Accounting',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-318',
        courseTitle: 'Engineering Simulation Lab',
        credit: 1,
        contactHours: 2,
      },
    ],
    total: 12,
    contactHours: 15,
  },
  {
    year: 2,
    semester: 1,
    title: 'Second Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-205',
        courseTitle: 'Electronics-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-206',
        courseTitle: 'Electronics-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'CSE-203',
        courseTitle: 'Programming Language',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CSE-204',
        courseTitle: 'Programming Language Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'MTH-201',
        courseTitle: 'Linear Algebra and Complex Variables',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'BBA-201',
        courseTitle: 'Business Communication',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 2,
    semester: 2,
    title: 'Second Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-203',
        courseTitle: 'Electrical Machines-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-204',
        courseTitle: 'Electrical Machines-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-211',
        courseTitle: 'Semiconductor Device',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'MTH-203',
        courseTitle: 'Probability and Statistics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'BBA-207',
        courseTitle: 'Industrial and Operational Management',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 13,
    contactHours: 14,
  },
  {
    year: 2,
    semester: 3,
    title: 'Second Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-207',
        courseTitle: 'Digital Logic Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-208',
        courseTitle: 'Digital Logic Design Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-209',
        courseTitle: 'Electrical Machines-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-210',
        courseTitle: 'Electrical Machines-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'ME-201',
        courseTitle: 'Mechanical Engineering Fundamentals',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'MTH-205',
        courseTitle: 'Co-ordinate Geometry and Vector Analysis',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 3,
    semester: 1,
    title: 'Third Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-301',
        courseTitle: 'Digital Electronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-302',
        courseTitle: 'Digital Electronics Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-303',
        courseTitle: 'Signals and Systems',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-304',
        courseTitle: 'Signals and Systems Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'EEE-311',
        courseTitle: 'Communication Engineering',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-312',
        courseTitle: 'Communication Engineering Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 7,
        courseCode: 'MTH-301',
        courseTitle: 'Numerical Methods and Fourier and Laplace Transformation',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 15,
    contactHours: 18,
  },
  {
    year: 3,
    semester: 2,
    title: 'Third Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-305',
        courseTitle: 'Electromagnetic Fields and Waves',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-309',
        courseTitle: 'Digital Signal Processing',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'EEE-310',
        courseTitle: 'Digital Signal Processing Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 4,
        courseCode: 'EEE-315',
        courseTitle: 'Electrical Measurements and Instrumentation',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-316',
        courseTitle: 'Electrical Measurements and Instrumentation Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'EEE-329',
        courseTitle: 'Electrical Machines-III',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 3,
    semester: 3,
    title: 'Third Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-307',
        courseTitle: 'Microprocessor and Interfacing',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-308',
        courseTitle: 'Microprocessor and Interfacing Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-345',
        courseTitle: 'Transmission and Distribution',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-347',
        courseTitle: 'Power Systems Engineering',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-449',
        courseTitle: 'Power Plant Engineering',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 13,
    contactHours: 14,
  },
  {
    year: 4,
    semester: 1,
    title: 'Fourth Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-401',
        courseTitle: 'Control Systems',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-402',
        courseTitle: 'Control Systems Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-413',
        courseTitle: 'Electrical Engineering Materials',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-463',
        courseTitle: 'VLSI Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-464',
        courseTitle: 'VLSI Design Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'EEE-471',
        courseTitle: 'Wireless and Mobile Communication',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 4,
    semester: 2,
    title: 'Fourth Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-431',
        courseTitle: 'Power Electronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-432',
        courseTitle: 'Power Electronics Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-453',
        courseTitle: 'Power System Protection',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-455',
        courseTitle: 'Renewable Energy',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-459',
        courseTitle: 'Optoelectronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-473',
        courseTitle: 'Optical Fiber Communications',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 16,
    contactHours: 17,
  },
  {
    year: 4,
    semester: 3,
    title: 'Fourth Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-498',
        courseTitle: 'Project/Thesis',
        credit: 6,
        contactHours: 6,
      },
    ],
    total: 6,
    contactHours: 6,
  },
];

// Diploma Background Students - Evening Program
export const eeeEveningSemesterData: Semester[] = [
  {
    year: 1,
    semester: 1,
    title: 'First Year, First Semester (Exempted)',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-101',
        courseTitle: 'Electrical Circuits-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-102',
        courseTitle: 'Electrical Circuits-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'MTH-101',
        courseTitle: 'Differential and Integral Calculus',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'BBA-103',
        courseTitle: 'Financial and Managerial Accounting',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 10,
    contactHours: 11,
    isExempted: true,
  },
  {
    year: 1,
    semester: 2,
    title: 'First Year, Second Semester (Exempted)',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-100',
        courseTitle: 'Electrical Drawing and Drafting Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 2,
        courseCode: 'PHY-101',
        courseTitle: 'Physics-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'PHY-102',
        courseTitle: 'Physics-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 4,
        courseCode: 'BBA-207',
        courseTitle: 'Industrial and Operational Management',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 8,
    contactHours: 10,
    isExempted: true,
  },
  {
    year: 1,
    semester: 3,
    title: 'First Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-103',
        courseTitle: 'Electrical Circuits-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-104',
        courseTitle: 'Electrical Circuits-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'MTH-103',
        courseTitle: 'Differential Equations',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CHM-101',
        courseTitle: 'Chemistry',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'CHM-102',
        courseTitle: 'Chemistry Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'PHY-103',
        courseTitle: 'Physics-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 7,
        courseCode: 'PHY-104',
        courseTitle: 'Physics-II Lab',
        credit: 1,
        contactHours: 2,
      },
    ],
    total: 15,
    contactHours: 18,
  },
  {
    year: 2,
    semester: 1,
    title: 'Second Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-201',
        courseTitle: 'Electronics-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-202',
        courseTitle: 'Electronics-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'CSE-203',
        courseTitle: 'Programming Language',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'CSE-204',
        courseTitle: 'Programming Language Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'MTH-201',
        courseTitle: 'Linear Algebra and Complex Variables',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'ENG-101',
        courseTitle: 'Oral and Written English',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 7,
        courseCode: 'GED-101',
        courseTitle:
          'Bangladesh Studies (History of Independence of Bangladesh)',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 17,
    contactHours: 19,
  },
  {
    year: 2,
    semester: 2,
    title: 'Second Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-203',
        courseTitle: 'Electrical Machines-I',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-204',
        courseTitle: 'Electrical Machines-I Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-211',
        courseTitle: 'Semiconductor Device',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'ME-201',
        courseTitle: 'Mechanical Engineering Fundamentals',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'MTH-203',
        courseTitle: 'Probability and Statistics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'BBA-201',
        courseTitle: 'Business Communication',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 16,
    contactHours: 17,
  },
  {
    year: 2,
    semester: 3,
    title: 'Second Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-205',
        courseTitle: 'Electronics-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-206',
        courseTitle: 'Electronics-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-207',
        courseTitle: 'Digital Logic Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-208',
        courseTitle: 'Digital Logic Design Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'EEE-209',
        courseTitle: 'Electrical Machines-II',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-210',
        courseTitle: 'Electrical Machines-II Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 7,
        courseCode: 'MTH-205',
        courseTitle: 'Co-ordinate Geometry and Vector Analysis',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 15,
    contactHours: 18,
  },
  {
    year: 3,
    semester: 1,
    title: 'Third Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-301',
        courseTitle: 'Digital Electronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-302',
        courseTitle: 'Digital Electronics Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-303',
        courseTitle: 'Signals and Systems',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-304',
        courseTitle: 'Signals and Systems Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 5,
        courseCode: 'EEE-311',
        courseTitle: 'Communication Engineering',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-312',
        courseTitle: 'Communication Engineering Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 7,
        courseCode: 'MTH-301',
        courseTitle: 'Numerical Methods and Fourier and Laplace Transformation',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 15,
    contactHours: 18,
  },
  {
    year: 3,
    semester: 2,
    title: 'Third Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-305',
        courseTitle: 'Electromagnetic Fields and Waves',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-309',
        courseTitle: 'Digital Signal Processing',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 3,
        courseCode: 'EEE-310',
        courseTitle: 'Digital Signal Processing Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 4,
        courseCode: 'EEE-315',
        courseTitle: 'Electrical Measurements and Instrumentation',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-316',
        courseTitle: 'Electrical Measurements and Instrumentation Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'EEE-329',
        courseTitle: 'Electrical Machines-III',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 3,
    semester: 3,
    title: 'Third Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-307',
        courseTitle: 'Microprocessor and Interfacing',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-308',
        courseTitle: 'Microprocessor and Interfacing Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-318',
        courseTitle: 'Engineering Simulation Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 4,
        courseCode: 'EEE-345',
        courseTitle: 'Transmission and Distribution',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-347',
        courseTitle: 'Power Systems Engineering',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-449',
        courseTitle: 'Power Plant Engineering',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 4,
    semester: 1,
    title: 'Fourth Year, First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-401',
        courseTitle: 'Control System',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-402',
        courseTitle: 'Control System Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-413',
        courseTitle: 'Electrical Engineering Materials',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-463',
        courseTitle: 'VLSI Design',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-464',
        courseTitle: 'VLSI Design Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 6,
        courseCode: 'EEE-471',
        courseTitle: 'Wireless and Mobile Communication',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 14,
    contactHours: 16,
  },
  {
    year: 4,
    semester: 2,
    title: 'Fourth Year, Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-431',
        courseTitle: 'Power Electronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 2,
        courseCode: 'EEE-432',
        courseTitle: 'Power Electronics Lab',
        credit: 1,
        contactHours: 2,
      },
      {
        slNo: 3,
        courseCode: 'EEE-453',
        courseTitle: 'Power System Protection',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 4,
        courseCode: 'EEE-455',
        courseTitle: 'Renewable Energy',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 5,
        courseCode: 'EEE-459',
        courseTitle: 'Optoelectronics',
        credit: 3,
        contactHours: 3,
      },
      {
        slNo: 6,
        courseCode: 'EEE-473',
        courseTitle: 'Optical Fiber Communications',
        credit: 3,
        contactHours: 3,
      },
    ],
    total: 16,
    contactHours: 17,
  },
  {
    year: 4,
    semester: 3,
    title: 'Fourth Year, Third Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'EEE-498',
        courseTitle: 'Project/Thesis',
        credit: 6,
        contactHours: 6,
      },
    ],
    total: 6,
    contactHours: 6,
  },
];
