import type {
  Course,
  CoursePrefix,
  Semester,
} from '@/app/(programs)/_config/curriculum';

export const llbCoursePrefixes: CoursePrefix[] = [
  { symbol: 'ENG', name: 'English' },
  { symbol: 'CSE', name: 'Computer Science and Engineering' },
  { symbol: 'LAW', name: 'Law' },
  { symbol: 'GED', name: 'General Education' },
];

export const llbCoreCoursesData: Course[] = [
  { sl: 1, code: 'ENG 101', title: 'Foundation English', credits: 3 },
  { sl: 2, code: 'CSE 101', title: 'Computer Fundamentals', credits: 3 },
  { sl: 3, code: 'LAW 101', title: 'English for Law', credits: 3 },
  { sl: 4, code: 'LAW 106', title: 'Legal System of Bangladesh', credits: 3 },
  { sl: 5, code: 'LAW 109', title: 'Law of Trust and Equity', credits: 3 },
  { sl: 6, code: 'GED 102', title: 'Bangladesh Studies', credits: 3 },
  { sl: 7, code: 'GED 103', title: 'Introduction to Sociology', credits: 3 },
  { sl: 8, code: 'LAW 102', title: 'Jurisprudence', credits: 3 },
  { sl: 9, code: 'LAW 105', title: 'Law of Contract', credits: 3 },
  { sl: 10, code: 'LAW 108', title: 'Law of Tort', credits: 3 },
  { sl: 11, code: 'GED 104', title: 'Introduction to Psychology', credits: 3 },
  { sl: 12, code: 'LAW 107', title: 'Muslim Law', credits: 3 },
  { sl: 13, code: 'LAW 202', title: 'Law of Transfer of Property', credits: 3 },
  { sl: 14, code: 'LAW 203', title: 'Company Law', credits: 3 },
  { sl: 15, code: 'LAW 206', title: 'Criminology', credits: 3 },
  {
    sl: 16,
    code: 'LAW 103',
    title: 'Constitutional Law of Bangladesh',
    credits: 4,
  },
  {
    sl: 17,
    code: 'LAW 201',
    title: 'Law of Registration and Public Demand Recovery',
    credits: 3,
  },
  { sl: 18, code: 'LAW 205', title: 'Labor and Industrial Law', credits: 3 },
  { sl: 19, code: 'LAW 209', title: 'Roman and Hindu Law', credits: 3 },
  { sl: 20, code: 'LAW 305', title: 'Insurance & Maritime Law', credits: 3 },
  { sl: 21, code: 'LAW 306', title: 'Interpretation of Statutes', credits: 3 },
  { sl: 22, code: 'LAW 204', title: 'Land Laws of Bangladesh', credits: 4 },
  { sl: 23, code: 'LAW 208', title: 'Criminal Law (Substantive)', credits: 3 },
  {
    sl: 24,
    code: 'LAW 307',
    title: 'Banking and Securities Exchange Laws',
    credits: 3,
  },
  { sl: 25, code: 'LAW 403', title: 'Administrative Law', credits: 3 },
  {
    sl: 26,
    code: 'LAW 406',
    title: 'Laws Relating to Taxation and Customs',
    credits: 3,
  },
  { sl: 27, code: 'LAW 207', title: 'Laws on Criminal Procedure', credits: 3 },
  {
    sl: 28,
    code: 'LAW 303',
    title: 'Business Law (Sale, Carriage, Partnership)',
    credits: 3,
  },
  { sl: 29, code: 'LAW 304', title: 'Law of Evidence', credits: 4 },
  {
    sl: 30,
    code: 'LAW 308',
    title: 'Law of Intellectual Property',
    credits: 4,
  },
  { sl: 31, code: 'LAW 309', title: 'Legal Drafting (Criminal)', credits: 3 },
  {
    sl: 32,
    code: 'LAW 301',
    title: 'Law of Specific Relief and Limitation',
    credits: 3,
  },
  { sl: 33, code: 'LAW 302', title: 'Laws on Civil Procedure', credits: 4 },
  { sl: 34, code: 'LAW 401', title: 'Legal Drafting (Civil)', credits: 3 },
  { sl: 35, code: 'LAW 404', title: 'International Trade Law', credits: 3 },
  { sl: 36, code: 'LAW 407', title: 'Law of Human Rights', credits: 4 },
  {
    sl: 37,
    code: 'LAW 402',
    title: 'Alternative Dispute Resolution',
    credits: 3,
  },
  { sl: 38, code: 'LAW 405', title: 'Public International Law', credits: 4 },
  {
    sl: 39,
    code: 'LAW 408',
    title: 'Legislation and Legislative Drafting',
    credits: 3,
  },
  {
    sl: 40,
    code: 'LAW 409',
    title: 'Professional Conduct and Etiquette, and Advocacy Workshop',
    credits: 3,
  },
  { sl: 41, code: 'LAW 410', title: 'Legal Research Methodology', credits: 3 },
];

export const bssEcoCoreCoursesData: Course[] = [
  {
    sl: 1,
    code: 'ECO:101',
    title: 'Introduction to Microeconomics',
    credits: 3,
  },
  {
    sl: 2,
    code: 'ECO:102',
    title: 'Introduction to Macroeconomics',
    credits: 3,
  },
  {
    sl: 3,
    code: 'ECO:205',
    title: 'Mathematics for Economics',
    credits: 3,
  },
  {
    sl: 4,
    code: 'ECO:105',
    title: 'Intermediate Microeconomics I',
    credits: 3,
  },
  {
    sl: 5,
    code: 'ECO:106',
    title: 'Intermediate Macroeconomics I',
    credits: 3,
  },
  {
    sl: 6,
    code: 'ECO:109',
    title: 'Intermediate Microeconomics II',
    credits: 3,
  },
  {
    sl: 7,
    code: 'ECO:201',
    title: 'Intermediate Macroeconomics II',
    credits: 3,
  },
  {
    sl: 8,
    code: 'ECO:210',
    title: 'Econometrics I',
    credits: 3,
  },
  {
    sl: 9,
    code: 'ECO:302',
    title: 'Econometrics II',
    credits: 3,
  },
  {
    sl: 10,
    code: 'ECO:212',
    title: 'History of Economic Thoughts',
    credits: 3,
  },
  {
    sl: 11,
    code: 'ECO:303',
    title: 'Development Economics',
    credits: 3,
  },
  {
    sl: 12,
    code: 'ECO:211',
    title: 'International Trade',
    credits: 3,
  },
  {
    sl: 13,
    code: 'ECO:306',
    title: 'International Finance',
    credits: 3,
  },
  {
    sl: 14,
    code: 'ECO:401',
    title: 'Advanced Microeconomics',
    credits: 3,
  },
  {
    sl: 15,
    code: 'ECO:403',
    title: 'Advanced Macroeconomics',
    credits: 3,
  },
  {
    sl: 16,
    code: 'ECO:305',
    title: 'Public Economics',
    credits: 3,
  },
  {
    sl: 17,
    code: 'ECO:402',
    title: 'Money and Banking',
    credits: 3,
  },
  {
    sl: 18,
    code: 'ECO:207',
    title: 'Bangladesh Economy',
    credits: 3,
  },
  {
    sl: 19,
    code: 'ECO:404',
    title: 'Research Methodology',
    credits: 3,
  },
  {
    sl: 20,
    code: 'ECO:405',
    title: 'Undergraduate Research Report',
    credits: 3,
  },
];

export const bssEcoGeneralCoursesData: Course[] = [
  {
    sl: 1,
    code: 'ECO:103',
    title: 'Fundamentals of Mathematics',
    credits: 3,
  },
  {
    sl: 2,
    code: 'ECO:104',
    title: 'Fundamentals of Computer Application',
    credits: 3,
  },
  {
    sl: 3,
    code: 'ECO:108',
    title: 'Fundamentals of English',
    credits: 3,
  },
  {
    sl: 4,
    code: 'ECO:112',
    title: 'Ethics, Equity and Justice',
    credits: 3,
  },
  {
    sl: 5,
    code: 'ECO:111',
    title: 'Bangladesh Studies',
    credits: 3,
  },
];

export const bssEcoNonMajorCoursesData: Course[] = [
  {
    sl: 1,
    code: 'ECO:107',
    title: 'Statistics I',
    credits: 3,
  },
  {
    sl: 2,
    code: 'ECO:202',
    title: 'Statistics II',
    credits: 3,
  },
  {
    sl: 3,
    code: 'ECO:208',
    title: 'Introduction to Sociology',
    credits: 3,
  },
  {
    sl: 4,
    code: 'ECO:204',
    title: 'Introduction to Politics and Governance',
    credits: 3,
  },
  {
    sl: 5,
    code: 'ECO:209',
    title: 'Introduction to Anthropology',
    credits: 3,
  },
  {
    sl: 6,
    code: 'ECO:203',
    title: 'Introduction to Finance and Accounting',
    credits: 3,
  },
  {
    sl: 7,
    code: 'ECO:304',
    title: 'International Economic Policy and System',
    credits: 3,
  },
  {
    sl: 8,
    code: 'ECO:110',
    title: 'Introduction to Business',
    credits: 3,
  },
  {
    sl: 9,
    code: 'ECO:206',
    title: 'Mathematics I: (Linear Algebra and Calculus)',
    credits: 3,
  },
  {
    sl: 10,
    code: 'ECO:301',
    title: 'Mathematics II: (Optimization Techniques)',
    credits: 3,
  },
];

export const bssEcoElectiveCoursesData: Course[] = [
  {
    sl: 1,
    code: 'ECO:307',
    title: 'Political Economy of Developed and Under Developed Countries',
    credits: 3,
  },
  {
    sl: 2,
    code: 'ECO:308',
    title: 'Gender and Development',
    credits: 3,
  },
  {
    sl: 3,
    code: 'ECO:309',
    title: 'Agricultural Economics',
    credits: 3,
  },
  {
    sl: 4,
    code: 'ECO:310',
    title: 'Labor Economics',
    credits: 3,
  },
  {
    sl: 5,
    code: 'ECO:311',
    title: 'Industrial Economics',
    credits: 3,
  },
  {
    sl: 6,
    code: 'ECO:312',
    title: 'Urban Economics',
    credits: 3,
  },
  {
    sl: 7,
    code: 'ECO:313',
    title: 'Poverty in Bangladesh',
    credits: 3,
  },
  {
    sl: 8,
    code: 'ECO:314',
    title: 'Transnational Corporation',
    credits: 3,
  },
  {
    sl: 9,
    code: 'ECO:315',
    title: 'Advanced Econometrics I',
    credits: 3,
  },
  {
    sl: 10,
    code: 'ECO:316',
    title: 'Environmental Economics',
    credits: 3,
  },
  {
    sl: 11,
    code: 'ECO:317',
    title: 'Health Economics',
    credits: 3,
  },
  {
    sl: 12,
    code: 'ECO:318',
    title: 'Natural Resources: Conflict and War',
    credits: 3,
  },
  {
    sl: 13,
    code: 'ECO:406',
    title: 'International Business',
    credits: 3,
  },
];

export const llbSemesterData: Semester[] = [
  {
    year: 1,
    semester: 1,
    title: 'First Year First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'ENG 101',
        courseTitle: 'Foundation English',
        credit: 3,
      },
      {
        slNo: 2,
        courseCode: 'CSE 101',
        courseTitle: 'Computer Fundamentals',
        credit: 3,
      },
      {
        slNo: 3,
        courseCode: 'LAW 101',
        courseTitle: 'English for Law',
        credit: 3,
      },
      {
        slNo: 4,
        courseCode: 'LAW 106',
        courseTitle: 'Legal System of Bangladesh',
        credit: 3,
      },
      {
        slNo: 5,
        courseCode: 'LAW 109',
        courseTitle: 'Law of Trust and Equity',
        credit: 3,
      },
    ],
    total: 15,
  },
  {
    year: 1,
    semester: 2,
    title: 'First Year Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'GED 102',
        courseTitle: 'Bangladesh Studies',
        credit: 3,
      },
      {
        slNo: 2,
        courseCode: 'GED 103',
        courseTitle: 'Introduction to Sociology',
        credit: 3,
      },
      {
        slNo: 3,
        courseCode: 'LAW 102',
        courseTitle: 'Jurisprudence',
        credit: 3,
      },
      {
        slNo: 4,
        courseCode: 'LAW 105',
        courseTitle: 'Law of Contract',
        credit: 3,
      },
      { slNo: 5, courseCode: 'LAW 108', courseTitle: 'Law of Tort', credit: 3 },
    ],
    total: 15,
  },
  {
    year: 2,
    semester: 1,
    title: 'Second Year First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'GED 104',
        courseTitle: 'Introduction to Psychology',
        credit: 3,
      },
      { slNo: 2, courseCode: 'LAW 107', courseTitle: 'Muslim Law', credit: 3 },
      {
        slNo: 3,
        courseCode: 'LAW 202',
        courseTitle: 'Law of Transfer of Property',
        credit: 3,
      },
      { slNo: 4, courseCode: 'LAW 203', courseTitle: 'Company Law', credit: 3 },
      { slNo: 5, courseCode: 'LAW 206', courseTitle: 'Criminology', credit: 3 },
    ],
    total: 15,
  },
  {
    year: 2,
    semester: 2,
    title: 'Second Year Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'LAW 103',
        courseTitle: 'Constitutional Law of Bangladesh',
        credit: 4,
      },
      {
        slNo: 2,
        courseCode: 'LAW 201',
        courseTitle: 'Law of Registration and Public Demand Recovery',
        credit: 3,
      },
      {
        slNo: 3,
        courseCode: 'LAW 205',
        courseTitle: 'Labor and Industrial Law',
        credit: 3,
      },
      {
        slNo: 4,
        courseCode: 'LAW 209',
        courseTitle: 'Roman and Hindu Law',
        credit: 3,
      },
      {
        slNo: 5,
        courseCode: 'LAW 305',
        courseTitle: 'Insurance & Maritime Law',
        credit: 3,
      },
      {
        slNo: 6,
        courseCode: 'LAW 306',
        courseTitle: 'Interpretation of Statutes',
        credit: 3,
      },
    ],
    total: 19,
  },
  {
    year: 3,
    semester: 1,
    title: 'Third Year First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'LAW 204',
        courseTitle: 'Land Laws of Bangladesh',
        credit: 4,
      },
      {
        slNo: 2,
        courseCode: 'LAW 208',
        courseTitle: 'Criminal Law (Substantive)',
        credit: 3,
      },
      {
        slNo: 3,
        courseCode: 'LAW 307',
        courseTitle: 'Banking and Securities Exchange Laws',
        credit: 3,
      },
      {
        slNo: 4,
        courseCode: 'LAW 403',
        courseTitle: 'Administrative Law',
        credit: 3,
      },
      {
        slNo: 5,
        courseCode: 'LAW 406',
        courseTitle: 'Laws Relating to Taxation and Customs',
        credit: 3,
      },
    ],
    total: 16,
  },
  {
    year: 3,
    semester: 2,
    title: 'Third Year Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'LAW 207',
        courseTitle: 'Laws on Criminal Procedure',
        credit: 3,
      },
      {
        slNo: 2,
        courseCode: 'LAW 303',
        courseTitle: 'Business Law (Sale, Carriage, Partnership)',
        credit: 3,
      },
      {
        slNo: 3,
        courseCode: 'LAW 304',
        courseTitle: 'Law of Evidence',
        credit: 4,
      },
      {
        slNo: 4,
        courseCode: 'LAW 308',
        courseTitle: 'Law of Intellectual Property',
        credit: 4,
      },
      {
        slNo: 5,
        courseCode: 'LAW 309',
        courseTitle: 'Legal Drafting (Criminal)',
        credit: 3,
      },
    ],
    total: 17,
  },
  {
    year: 4,
    semester: 1,
    title: 'Fourth Year First Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'LAW 301',
        courseTitle: 'Law of Specific Relief and Limitation',
        credit: 3,
      },
      {
        slNo: 2,
        courseCode: 'LAW 302',
        courseTitle: 'Laws on Civil Procedure',
        credit: 4,
      },
      {
        slNo: 3,
        courseCode: 'LAW 401',
        courseTitle: 'Legal Drafting (Civil)',
        credit: 3,
      },
      {
        slNo: 4,
        courseCode: 'LAW 404',
        courseTitle: 'International Trade Law',
        credit: 3,
      },
      {
        slNo: 5,
        courseCode: 'LAW 407',
        courseTitle: 'Law of Human Rights',
        credit: 4,
      },
    ],
    total: 17,
  },
  {
    year: 4,
    semester: 2,
    title: 'Fourth Year Second Semester',
    courses: [
      {
        slNo: 1,
        courseCode: 'LAW 402',
        courseTitle: 'Alternative Dispute Resolution',
        credit: 3,
      },
      {
        slNo: 2,
        courseCode: 'LAW 405',
        courseTitle: 'Public International Law',
        credit: 4,
      },
      {
        slNo: 3,
        courseCode: 'LAW 408',
        courseTitle: 'Legislation and Legislative Drafting',
        credit: 3,
      },
      {
        slNo: 4,
        courseCode: 'LAW 409',
        courseTitle:
          'Professional Conduct and Etiquette, and Advocacy Workshop',
        credit: 3,
      },
      {
        slNo: 5,
        courseCode: 'LAW 410',
        courseTitle: 'Legal Research Methodology',
        credit: 3,
      },
    ],
    total: 16,
  },
];
