import type {
	// Assuming 'Course' and other base types are defined as before
	Course,
	CoursePrefix,
	CurriculumSummary,
	ElectiveCourseGroup,
	PerformanceEvaluation,
	ProgramDetails,
	Semester,
} from '@/app/programs/_config/curriculum';

// This is the new, more descriptive type for the Civil electives

export const civilSemesterInfo = {
	spring: 'January-April',
	summer: 'May-August',
	fall: 'September-December',
};

export const civilRegularProgramDetails: ProgramDetails = {
	degreeName: 'Bachelor of Science in Civil Engineering',
	duration: {
		years: 4,
		semesters: 12,
	},
	creditHours: 165,
	courseLoad: '16 Weeks/Semester',
	minimumGPA: 2.2,
	backgroundStudents: 'For H.S.C. Background Students',
};

export const civilEveningProgramDetails: ProgramDetails = {
	degreeName: 'Bachelor of Science in Civil Engineering',
	duration: {
		years: 4,
		semesters: 12,
	},
	creditHours: '146 (19 waived)',
	courseLoad: '16 Weeks/Semester',
	minimumGPA: 2.2,
	backgroundStudents: 'For Diploma in Engg. Background Students',
	waiverInfo: '19 credits are waived for students with a Diploma in Engineering background.',
};

export const civilPerformanceEvaluation: PerformanceEvaluation[] = [
	{
		category: '(a) Theory Courses:',
		criteria: [
			{
				item: 'Class participation (i.e. attendance)',
				percentage: '20%',
			},
			{
				item: 'Class tests, presentations and assignments',
				percentage: '20%',
			},
			{ item: 'Midterm Examination', percentage: '30%' },
			{ item: 'Final Examination', percentage: '30%' },
		],
	},
	{
		category: '(b) Courses on Laboratory/Sessional/Field Work:',
		criteria: [
			{ item: 'Class participation and attendance', percentage: '20%' },
			{ item: 'Quiz', percentage: '20%' },
			{ item: 'Viva Voce', percentage: '20%' },
			{ item: 'Performance/Reports', percentage: '40%' },
		],
	},
	{
		category: '(c) Project and Thesis:',
		criteria: [
			{ item: 'Attendance', percentage: '10%' },
			{ item: 'Presentation and Viva Voce', percentage: '20%' },
			{ item: 'Co-Supervisor', percentage: '20%' },
			{ item: 'Supervisor', percentage: '50%' },
		],
	},
];

export const civilCoreCoursesData: Course[] = [
	{
		sl: 1,
		code: 'CE 100',
		title: 'Civil Engineering Drawing',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 2,
		code: 'CE 101',
		title: 'Analytic Mechanics',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 3,
		code: 'CE 102',
		title: 'Computer Aided Drafting',
		credits: 1,
		contactHours: 2,
	},
	{ sl: 4, code: 'CE 103', title: 'Surveying', credits: 4, contactHours: 4 },
	{
		sl: 5,
		code: 'CE 104',
		title: 'Practical Surveying',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 6,
		code: 'CE 105',
		title: 'Engineering Materials',
		credits: 4,
		contactHours: 4,
	},
	{
		sl: 7,
		code: 'CE 107',
		title: 'Introduction to Civil Engineering',
		credits: 2,
		contactHours: 2,
	},
	{
		sl: 8,
		code: 'CE 108',
		title: 'Quantity Surveying',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 9,
		code: 'CE 201',
		title: 'Professional Practice and Communication',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 10,
		code: 'CE 202',
		title: 'Engineering Materials Lab',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 11,
		code: 'CE 203',
		title: 'Engineering Geology and Geomorphology',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 12,
		code: 'CE 204',
		title: 'Computer Programming Sessional',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 13,
		code: 'CE 205',
		title: 'Numerical Methods',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 14,
		code: 'CE 206',
		title: 'Computer Fundamentals',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 15,
		code: 'CE 211',
		title: 'Mechanics of Solids-I',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 16,
		code: 'CE 212',
		title: 'Structural Mechanics and Materials Lab',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 17,
		code: 'CE 213',
		title: 'Mechanics of Solids-II',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 18,
		code: 'CE 231',
		title: 'Principles of Soil Mechanics',
		credits: 4,
		contactHours: 4,
	},
	{
		sl: 19,
		code: 'CE 251',
		title: 'Fluid Mechanics',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 20,
		code: 'CE 252',
		title: 'Fluid Mechanics Lab',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 21,
		code: 'CE 300',
		title: 'Details of Construction Sessional',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 22,
		code: 'CE 311',
		title: 'Design of Concrete Structures-I',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 23,
		code: 'CE 312',
		title: 'Design of Concrete Structures Sessional-I',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 24,
		code: 'CE 313',
		title: 'Design of Concrete Structures-II',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 25,
		code: 'CE 315',
		title: 'Structural Analysis-I',
		credits: 4,
		contactHours: 4,
	},
	{
		sl: 26,
		code: 'CE 317',
		title: 'Structural Analysis-II',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 27,
		code: 'CE 321',
		title: 'Environmental Engineering-I',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 28,
		code: 'CE 322',
		title: 'Environmental Engineering Lab-I',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 29,
		code: 'CE 323',
		title: 'Environmental Engineering-II',
		credits: 4,
		contactHours: 4,
	},
	{
		sl: 30,
		code: 'CE 331',
		title: 'Geotechnical Engineering-I',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 31,
		code: 'CE 332',
		title: 'Geotechnical Engineering Lab',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 32,
		code: 'CE 333',
		title: 'Geotechnical Engineering-II',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 33,
		code: 'CE 341',
		title: 'Transportation Engineering-I',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 34,
		code: 'CE 351',
		title: 'Open Channel Flow',
		credits: 4,
		contactHours: 4,
	},
	{
		sl: 35,
		code: 'CE 352',
		title: 'Open Channel Flow Lab',
		credits: 1,
		contactHours: 2,
	},
	{ sl: 36, code: 'CE 353', title: 'Hydrology', credits: 3, contactHours: 3 },
	{
		sl: 37,
		code: 'CE 401',
		title: 'Project Planning and Construction Management',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 38,
		code: 'CE 411',
		title: 'Structural Analysis-III',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 39,
		code: 'CE 412',
		title: 'Engineering Computational Sessional',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 40,
		code: 'CE 413',
		title: 'Design of Steel Structures',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 41,
		code: 'CE 415',
		title: 'Prestressed Concrete',
		credits: 2,
		contactHours: 2,
	},
	{
		sl: 42,
		code: 'CE 416',
		title: 'Design of Concrete Structures Sessional-II',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 43,
		code: 'CE 418',
		title: 'Computer Aided Analysis & Design of Structures Sessional',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 44,
		code: 'CE 423',
		title: 'Solid and Hazardous Waste Management',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 45,
		code: 'CE 442',
		title: 'Transportation Engineering Lab-I',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 46,
		code: 'CE 443',
		title: 'Transportation Engineering-II',
		credits: 4,
		contactHours: 4,
	},
];

export const civilGeneralEducationCourses: Course[] = [
	{
		sl: 1,
		code: 'HUM 103',
		title: 'Principles of Accounting',
		credits: 2,
		contactHours: 2,
	},
	{
		sl: 2,
		code: 'HUM 107',
		title: 'Sociology and Moral Philosophy',
		credits: 2,
		contactHours: 2,
	},
	{
		sl: 3,
		code: 'HUM 201',
		title: 'History of Independence of Bangladesh',
		credits: 2,
		contactHours: 2,
	},
	{
		sl: 4,
		code: 'HUM 205',
		title: 'Engineering Economics',
		credits: 2,
		contactHours: 2,
	},
	{ sl: 5, code: 'ENG 201', title: 'English', credits: 3, contactHours: 3 },
	{
		sl: 6,
		code: 'ENG 202',
		title: 'Developing English Language Skills',
		credits: 1,
		contactHours: 2,
	},
];

export const civilBasicScienceCourses: Course[] = [
	{
		sl: 1,
		code: 'PHY 101',
		title: 'Physics-I: General Physics',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 2,
		code: 'PHY 102',
		title: 'Physics Lab',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 3,
		code: 'PHY 103',
		title: 'Physics-II: Modern Physics',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 4,
		code: 'CHM 101',
		title: 'General Chemistry',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 5,
		code: 'CHM 102',
		title: 'Chemistry Lab',
		credits: 1,
		contactHours: 2,
	},
	{
		sl: 6,
		code: 'MTH 101',
		title: 'Math-I: Differential and Integral Calculus',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 7,
		code: 'MTH 103',
		title: 'Math-II: Linear Algebra, Matrix and Statistics',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 8,
		code: 'MTH 205',
		title: 'Math-III: Differential Equations & Probability',
		credits: 3,
		contactHours: 3,
	},
	{
		sl: 9,
		code: 'MTH 207',
		title: 'Math-IV: Applied Mathematics for Engineers',
		credits: 3,
		contactHours: 3,
	},
];

export const civilOtherEngineeringCourses: Course[] = [
	{
		sl: 1,
		code: 'EEE 111',
		title: 'Basic Electrical Technology',
		credits: 3,
		contactHours: 3,
	},
];

export const civilProjectCourses: Course[] = [
	{
		sl: 1,
		code: 'CE 400',
		title: 'Project & Thesis',
		credits: 5,
		contactHours: 5,
	},
];

export const civilElectiveCourses: ElectiveCourseGroup[] = [
	{
		title: 'Structural Engineering',
		courses: [
			{
				sl: 1,
				code: 'CE 414',
				title: 'Design of Steel Structures Sessional',
				credits: 1,
				contactHours: 2,
			},
			{
				sl: 2,
				code: 'CE 417',
				title: 'Structural Dynamics & Earthquake Engineering',
				credits: 3,
				contactHours: 3,
			},
			{
				sl: 3,
				code: 'CE 419',
				title: 'Design of Steel Concrete Composite Structures',
				credits: 3,
				contactHours: 3,
			},
		],
	},
	{
		title: 'Environmental Engineering',
		courses: [
			{
				sl: 1,
				code: 'CE 424',
				title: 'Environmental Engineering Lab-II',
				credits: 1,
				contactHours: 2,
			},
			{
				sl: 2,
				code: 'CE 425',
				title: 'EIA and Environmental Pollution Management',
				credits: 3,
				contactHours: 3,
			},
			{
				sl: 3,
				code: 'CE 427',
				title: 'Environmental and Sustainable Development',
				credits: 3,
				contactHours: 3,
			},
		],
	},
	{
		title: 'Geotechnical Engineering',
		courses: [
			{
				sl: 1,
				code: 'CE 431',
				title: 'Earth Retaining Structures',
				credits: 3,
				contactHours: 3,
			},
			{
				sl: 2,
				code: 'CE 432',
				title: 'Geotechnical Engineering lab II',
				credits: 1,
				contactHours: 2,
			},
			{
				sl: 3,
				code: 'CE 433',
				title: 'Elementary Soil Dynamics',
				credits: 3,
				contactHours: 3,
			},
		],
	},
	{
		title: 'Transportation Engineering',
		courses: [
			{
				sl: 1,
				code: 'CE 441',
				title: 'Highway Drainage Management & Airport Engineering',
				credits: 3,
				contactHours: 3,
			},
			{
				sl: 2,
				code: 'CE 444',
				title: 'Transportation Engineering Lab-II',
				credits: 1,
				contactHours: 2,
			},
			{
				sl: 3,
				code: 'CE 445',
				title: 'Transportation Engineering-III: Traffic Engineering Management',
				credits: 3,
				contactHours: 3,
			},
		],
	},
	{
		title: 'Water Resource Engineering',
		courses: [
			{
				sl: 1,
				code: 'CE 451',
				title: 'River Engineering',
				credits: 3,
				contactHours: 3,
			},
			{
				sl: 2,
				code: 'CE 452',
				title: 'Hydraulic Structures Lab',
				credits: 1,
				contactHours: 2,
			},
			{
				sl: 3,
				code: 'CE 455',
				title: 'Irrigation and Flood Management',
				credits: 3,
				contactHours: 3,
			},
			{
				sl: 4,
				code: 'CE 457',
				title: 'Ground water Engineering',
				credits: 3,
				contactHours: 3,
			},
			{
				sl: 5,
				code: 'CE 459',
				title: 'Coastal Engineering',
				credits: 3,
				contactHours: 3,
			},
		],
	},
];

export const civilCoursePrefixes: CoursePrefix[] = [
	{ symbol: 'CE', name: 'Civil Engineering' },
	{ symbol: 'CHM', name: 'Chemistry' },
	{ symbol: 'EEE', name: 'Electrical and Electronics Engineering' },
	{ symbol: 'ENG', name: 'English' },
	{ symbol: 'HUM', name: 'Humanities and Social Sciences' },
	{ symbol: 'MTH', name: 'Mathematics' },
	{ symbol: 'PHY', name: 'Physics' },
];

export const civilCurriculumSummary: CurriculumSummary[] = [
	{
		category: 'General Education',
		theory_courses: 5,
		sessional_courses: 1,
		credits: 12,
	},
	{
		category: 'Basic Science and Mathematics',
		theory_courses: 7,
		sessional_courses: 2,
		credits: 23,
	},
	{
		category: 'Other Engineering Disciplines',
		theory_courses: 1,
		sessional_courses: 0,
		credits: 3,
	},
	{
		category: 'CE Core',
		theory_courses: 28,
		sessional_courses: 19,
		credits: 112,
	},
	{
		category: 'Elective',
		theory_courses: 4,
		sessional_courses: 3,
		credits: 15,
	},
];

// The semester data is unchanged from the previous correct version and is omitted here for brevity.
// civilRegularSemesterData and civilEveningSemesterData should be included here in the final file.

// Semester Data remains the same as the previously corrected version...
// HSC Background Students - Regular Program
export const civilRegularSemesterData: Semester[] = [
	{
		year: 1,
		semester: 1,
		title: '1st Year 1st Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 107',
				courseTitle: 'Introduction to Civil Engineering',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 2,
				courseCode: 'EEE 111',
				courseTitle: 'Basic Electrical Technology',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CHM 101',
				courseTitle: 'General Chemistry',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 4,
				courseCode: 'PHY 101',
				courseTitle: 'Physics-I: General Physics',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 5,
				courseCode: 'MTH 101',
				courseTitle: 'Math-I: Differential and Integral Calculus',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 6,
				courseCode: 'CE 100',
				courseTitle: 'Civil Engineering Drawing',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 15,
		contactHours: 16,
	},
	{
		year: 1,
		semester: 2,
		title: '1st Year 2nd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 103',
				courseTitle: 'Surveying',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 2,
				courseCode: 'CE 108',
				courseTitle: 'Quantity Surveying',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 3,
				courseCode: 'PHY 102',
				courseTitle: 'Physics Lab',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'PHY 103',
				courseTitle: 'Physics-II: Modern Physics',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 5,
				courseCode: 'MTH 103',
				courseTitle: 'Math-II: Linear Algebra, Matrix and Statistics',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 6,
				courseCode: 'CE 102',
				courseTitle: 'Computer Aided Drafting',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 13,
		contactHours: 16,
	},
	{
		year: 1,
		semester: 3,
		title: '1st Year 3rd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 101',
				courseTitle: 'Analytic Mechanics',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 105',
				courseTitle: 'Engineering Materials',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 3,
				courseCode: 'HUM 103',
				courseTitle: 'Principles of Accounting',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'HUM 107',
				courseTitle: 'Sociology and Moral Philosophy',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 104',
				courseTitle: 'Practical Surveying',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 6,
				courseCode: 'CHM 102',
				courseTitle: 'Chemistry Lab',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 13,
		contactHours: 15,
	},
	{
		year: 2,
		semester: 1,
		title: '2nd Year 1st Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 211',
				courseTitle: 'Mechanics of Solids-I',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'ENG 201',
				courseTitle: 'English',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'HUM 201',
				courseTitle: 'History of Independence of Bangladesh',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'MTH 205',
				courseTitle: 'Math-III: Differential Equations & Probability',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 5,
				courseCode: 'CE 202',
				courseTitle: 'Engineering Materials Lab',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 6,
				courseCode: 'CE 204',
				courseTitle: 'Computer Programming Sessional',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 7,
				courseCode: 'CE 206',
				courseTitle: 'Computer Fundamentals',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 14,
		contactHours: 17,
	},
	{
		year: 2,
		semester: 2,
		title: '2nd Year 2nd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 203',
				courseTitle: 'Engineering Geology and Geomorphology',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 205',
				courseTitle: 'Numerical Methods',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CE 213',
				courseTitle: 'Mechanics of Solids-II',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 4,
				courseCode: 'HUM 205',
				courseTitle: 'Engineering Economics',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'MTH 207',
				courseTitle: 'Math-IV: Applied Mathematics for Engineers',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 6,
				courseCode: 'ENG 202',
				courseTitle: 'Developing English Language Skills',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 15,
		contactHours: 16,
	},
	{
		year: 2,
		semester: 3,
		title: '2nd Year 3rd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 201',
				courseTitle: 'Professional Practice and Communication',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 231',
				courseTitle: 'Principles of Soil Mechanics',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 3,
				courseCode: 'CE 251',
				courseTitle: 'Fluid Mechanics',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 4,
				courseCode: 'CE 212',
				courseTitle: 'Structural Mechanics and Materials Lab',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 252',
				courseTitle: 'Fluid Mechanics Lab',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 12,
		contactHours: 14,
	},
	{
		year: 3,
		semester: 1,
		title: '3rd Year 1st Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 311',
				courseTitle: 'Design of Concrete Structures-I',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 315',
				courseTitle: 'Structural Analysis-I',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 3,
				courseCode: 'CE 321',
				courseTitle: 'Environmental Engineering-I',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 4,
				courseCode: 'CE 300',
				courseTitle: 'Details of Construction Sessional',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 332',
				courseTitle: 'Geotechnical Engineering Lab',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 12,
		contactHours: 14,
	},
	{
		year: 3,
		semester: 2,
		title: '3rd Year 2nd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 331',
				courseTitle: 'Geotechnical Engineering-I',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 351',
				courseTitle: 'Open Channel Flow',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 3,
				courseCode: 'CE 322',
				courseTitle: 'Environmental Engineering Lab-I',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'CE 313',
				courseTitle: 'Design of Concrete Structures-II',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 5,
				courseCode: 'CE 317',
				courseTitle: 'Structural Analysis-II',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 6,
				courseCode: 'CE 312',
				courseTitle: 'Design of Concrete Structures Sessional-I',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 15,
		contactHours: 17,
	},
	{
		year: 3,
		semester: 3,
		title: '3rd Year 3rd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 323',
				courseTitle: 'Environmental Engineering-II',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 2,
				courseCode: 'CE 333',
				courseTitle: 'Geotechnical Engineering-II',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CE 341',
				courseTitle: 'Transportation Engineering-I',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 4,
				courseCode: 'CE 353',
				courseTitle: 'Hydrology',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 5,
				courseCode: 'CE 352',
				courseTitle: 'Open Channel Flow Lab',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 14,
		contactHours: 15,
	},
	{
		year: 4,
		semester: 1,
		title: '4th Year 1st Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 401',
				courseTitle: 'Project Planning and Construction Management',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 411',
				courseTitle: 'Structural Analysis-III',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CE 443',
				courseTitle: 'Transportation Engineering-II',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 4,
				courseCode: 'CE 416',
				courseTitle: 'Design of Concrete Structures Sessional-II',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 442',
				courseTitle: 'Transportation Engineering Lab-I',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 6,
				courseCode: 'CE 423',
				courseTitle: 'Solid and Hazardous Waste Management',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 7,
				courseCode: 'CE 400',
				courseTitle: 'Project & Thesis',
				credit: 0,
				contactHours: 2,
			},
		],
		total: 15,
		contactHours: 19,
	},
	{
		year: 4,
		semester: 2,
		title: '4th Year 2nd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 413',
				courseTitle: 'Design of Steel Structures',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 418',
				courseTitle: 'Computer Aided Analysis & Design of Structures Sessional',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 3,
				courseCode: 'CE 415',
				courseTitle: 'Prestressed Concrete',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'CE 412',
				courseTitle: 'Engineering Computational Sessional',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Laboratory Course from Major Groups',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 6,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Theory Course from Major Groups',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 7,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Theory Course from Major Groups',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 8,
				courseCode: 'CE 400',
				courseTitle: 'Project & Thesis',
				credit: 0,
				contactHours: 2,
			},
		],
		total: 14,
		contactHours: 19,
	},
	{
		year: 4,
		semester: 3,
		title: '4th Year 3rd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Theory Course from Minor Groups',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Theory Course from Minor Groups',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Laboratory Course from Minor Groups',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Laboratory Course from Minor Groups',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 400',
				courseTitle: 'Project & Thesis',
				credit: 5,
				contactHours: 0,
			},
		],
		total: 13,
		contactHours: 10,
	},
];

// Diploma Background Students - Evening Program
export const civilEveningSemesterData: Semester[] = [
	{
		year: 1,
		semester: 1,
		title: '1st Year 1st Semester (Exempted)',
		courses: [
			{
				slNo: 1,
				courseCode: 'EEE 111',
				courseTitle: 'Basic Electrical Technology',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'PHY 101',
				courseTitle: 'Physics-I: General Physics',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'HUM 107',
				courseTitle: 'Sociology and Moral Philosophy',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'CE 100',
				courseTitle: 'Civil Engineering Drawing',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 9,
		contactHours: 10,
		isExempted: true,
	},
	{
		year: 1,
		semester: 2,
		title: '1st Year 2nd Semester (Exempted)',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 103',
				courseTitle: 'Surveying',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 2,
				courseCode: 'CE 107',
				courseTitle: 'Introduction to Civil Engineering',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 3,
				courseCode: 'HUM 103',
				courseTitle: 'Principles of Accounting',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'CE 102',
				courseTitle: 'Computer-Aided Drafting',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 104',
				courseTitle: 'Practical Surveying',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 10,
		contactHours: 12,
		isExempted: true,
	},
	{
		year: 1,
		semester: 3,
		title: '1st Year 3rd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 101',
				courseTitle: 'Analytic Mechanics',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CHM 101',
				courseTitle: 'General Chemistry',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'PHY 103',
				courseTitle: 'Physics-II: Modern Physics',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 4,
				courseCode: 'MTH 101',
				courseTitle: 'Math-I: Differential and Integral Calculus',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 5,
				courseCode: 'PHY 102',
				courseTitle: 'Physics Lab',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 6,
				courseCode: 'CHM 102',
				courseTitle: 'Chemistry Lab',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 14,
		contactHours: 16,
	},
	{
		year: 2,
		semester: 1,
		title: '2nd Year 1st Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 105',
				courseTitle: 'Engineering Materials',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 2,
				courseCode: 'MTH 103',
				courseTitle: 'Math-II: Linear Algebra, Matrix and Statistics',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CE 108',
				courseTitle: 'Quantity Surveying',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'CE 211',
				courseTitle: 'Mechanics of Solids-I',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 5,
				courseCode: 'ENG 201',
				courseTitle: 'English',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 6,
				courseCode: 'HUM 201',
				courseTitle: 'History of Independence of Bangladesh',
				credit: 2,
				contactHours: 2,
			},
		],
		total: 16,
		contactHours: 17,
	},
	{
		year: 2,
		semester: 2,
		title: '2nd Year 2nd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 203',
				courseTitle: 'Engineering Geology and Geomorphology',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 205',
				courseTitle: 'Numerical Methods',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'MTH 205',
				courseTitle: 'Math-III: Differential Equations & Probability',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 4,
				courseCode: 'CE 202',
				courseTitle: 'Engineering Materials Lab',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 204',
				courseTitle: 'Computer Programming Sessional',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 6,
				courseCode: 'CE 206',
				courseTitle: 'Computer Fundamentals',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 7,
				courseCode: 'CE 213',
				courseTitle: 'Mechanics of Solids-II',
				credit: 3,
				contactHours: 3,
			},
		],
		total: 15,
		contactHours: 18,
	},
	{
		year: 2,
		semester: 3,
		title: '2nd Year 3rd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 231',
				courseTitle: 'Principles of Soil Mechanics',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 2,
				courseCode: 'CE 251',
				courseTitle: 'Fluid Mechanics',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'HUM 205',
				courseTitle: 'Engineering Economics',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'MTH 207',
				courseTitle: 'Math-IV: Applied Mathematics for Engineers',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 5,
				courseCode: 'CE 212',
				courseTitle: 'Structural Mechanics and Materials Lab',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 6,
				courseCode: 'CE 252',
				courseTitle: 'Fluid Mechanics Lab',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 7,
				courseCode: 'ENG 202',
				courseTitle: 'Developing English Language Skills',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 15,
		contactHours: 18,
	},
	{
		year: 3,
		semester: 1,
		title: '3rd Year 1st Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 201',
				courseTitle: 'Professional Practice and Communication',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 315',
				courseTitle: 'Structural Analysis-I',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 3,
				courseCode: 'CE 331',
				courseTitle: 'Geotechnical Engineering-I',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 4,
				courseCode: 'CE 300',
				courseTitle: 'Details of Construction Sessional',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 351',
				courseTitle: 'Open Channel Flow',
				credit: 4,
				contactHours: 4,
			},
		],
		total: 15,
		contactHours: 16,
	},
	{
		year: 3,
		semester: 2,
		title: '3rd Year 2nd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 311',
				courseTitle: 'Design of Concrete Structures-I',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 321',
				courseTitle: 'Environmental Engineering-I',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CE 322',
				courseTitle: 'Environmental Engineering Lab-I',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'CE 332',
				courseTitle: 'Geotechnical Engineering Lab',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 317',
				courseTitle: 'Structural Analysis-II',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 6,
				courseCode: 'CE 333',
				courseTitle: 'Geotechnical Engineering-II',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 7,
				courseCode: 'CE 352',
				courseTitle: 'Open Channel Flow Lab',
				credit: 1,
				contactHours: 2,
			},
		],
		total: 15,
		contactHours: 18,
	},
	{
		year: 3,
		semester: 3,
		title: '3rd Year 3rd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 313',
				courseTitle: 'Design of Concrete Structures-II',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 353',
				courseTitle: 'Hydrology',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CE 312',
				courseTitle: 'Design of Concrete Structures Sessional-I',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'CE 323',
				courseTitle: 'Environmental Engineering-II',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 5,
				courseCode: 'CE 341',
				courseTitle: 'Transportation Engineering-I',
				credit: 3,
				contactHours: 3,
			},
		],
		total: 14,
		contactHours: 15,
	},
	{
		year: 4,
		semester: 1,
		title: '4th Year 1st Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 401',
				courseTitle: 'Project Planning and Construction Management',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 411',
				courseTitle: 'Structural Analysis-III',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CE 416',
				courseTitle: 'Design of Concrete Structures Sessional-II',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'CE 418',
				courseTitle: 'Computer Aided Analysis & Design of Structures Sessional',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 443',
				courseTitle: 'Transportation Engineering-II',
				credit: 4,
				contactHours: 4,
			},
			{
				slNo: 6,
				courseCode: 'CE 442',
				courseTitle: 'Transportation Engineering Lab-I',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 7,
				courseCode: 'CE 400',
				courseTitle: 'Project & Thesis',
				credit: 0,
				contactHours: 2,
			},
		],
		total: 13,
		contactHours: 18,
	},
	{
		year: 4,
		semester: 2,
		title: '4th Year 2nd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 413',
				courseTitle: 'Design of Steel Structures',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 2,
				courseCode: 'CE 423',
				courseTitle: 'Solid and Hazardous Waste Management',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Laboratory Course from Major Groups',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 4,
				courseCode: 'CE 412',
				courseTitle: 'Engineering Computational Sessional',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Theory Course from Major Groups',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 6,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Theory Course from Major Groups',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 7,
				courseCode: 'CE 400',
				courseTitle: 'Project & Thesis',
				credit: 0,
				contactHours: 2,
			},
		],
		total: 14,
		contactHours: 18,
	},
	{
		year: 4,
		semester: 3,
		title: '4th Year 3rd Semester',
		courses: [
			{
				slNo: 1,
				courseCode: 'CE 415',
				courseTitle: 'Prestressed Concrete',
				credit: 2,
				contactHours: 2,
			},
			{
				slNo: 2,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Theory Course from Minor Groups',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 3,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Theory Course from Minor Groups',
				credit: 3,
				contactHours: 3,
			},
			{
				slNo: 4,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Laboratory Course from Minor Groups',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 5,
				courseCode: 'CE 4XX',
				courseTitle: 'One Elective Laboratory Course from Minor Groups',
				credit: 1,
				contactHours: 2,
			},
			{
				slNo: 6,
				courseCode: 'CE 400',
				courseTitle: 'Project & Thesis',
				credit: 5,
				contactHours: 3,
			},
		],
		total: 15,
		contactHours: 15,
	},
];
